import React, { useState, useEffect } from 'react';
import {
  IonPage,
  IonContent,
  IonIcon,
} from '@ionic/react';
import {
  arrowBackOutline,
  personOutline,
  callOutline,
  locationOutline,
  alertCircleOutline,
  checkmarkCircleOutline,
  closeCircleOutline,
  medkitOutline,
  peopleOutline,
  shieldCheckmarkOutline,
  documentTextOutline,
  trashOutline,
  cloudUploadOutline,
  swapHorizontalOutline,
} from 'ionicons/icons';
import { useHistory, useParams } from 'react-router-dom';
import { ROUTES } from '../../constants/routes.constant';
import { Patient } from './PatientsPage';
import './branch-admin.css';

// ─── Dummy patient store (same data as PatientsPage) ──────────────────────────
// In a real app this would come from an API/store. For now we share the mock.
const MOCK_PATIENTS: Patient[] = [
  {
    id: 'PHX-2024-001',
    name: 'Priya Sharma',
    initials: 'PS',
    avatarColor: '#7c3aed',
    mobile: '+91 98765 43210',
    email: 'priya.sharma@email.com',
    gender: 'Female',
    dateOfBirth: '1990-03-15',
    age: 34,
    bloodGroup: 'B+',
    occupation: 'Software Engineer',
    status: 'Active',
    assignedHealer: 'Dr. Anjali Rao',
    lastVisitDate: '2024-01-15',
    regDate: '2023-06-10',
    emergencyContact: { name: 'Rajesh Sharma', relation: 'Husband', mobile: '+91 98888 12345' },
    medicalInfo: { conditions: ['Anxiety', 'Insomnia'], allergies: ['Penicillin'], medications: ['Melatonin'], notes: 'Chronic anxiety, referred by Dr. Kumar.' },
    credentials: { username: 'priya_sharma', passwordAutoGenerated: 'PHMS-5542', smsSent: true, emailSent: true },
    address: '12, Rose Garden Colony, Banjara Hills, Hyderabad - 500034',
    treatmentType: 'Pranic Psychotherapy',
    sessions: [],
    financials: { balanceDue: 1500, invoices: [] },
    documents: [],
    appointments: [],
    activityLogs: [],
    statusHistory: [],
    healerHistory: [],
    feedback: [],
  },
  {
    id: 'PHX-2024-002',
    name: 'Arjun Mehta',
    initials: 'AM',
    avatarColor: '#059669',
    mobile: '+91 87654 32109',
    email: 'arjun.mehta@email.com',
    gender: 'Male',
    dateOfBirth: '1985-07-22',
    age: 38,
    bloodGroup: 'O+',
    occupation: 'Teacher',
    status: 'Active',
    assignedHealer: 'Dr. Kevin Smith',
    lastVisitDate: '2024-01-12',
    regDate: '2023-08-20',
    emergencyContact: { name: 'Sunita Mehta', relation: 'Wife', mobile: '+91 87777 22222' },
    medicalInfo: { conditions: ['Depression'], allergies: [], medications: [], notes: 'Mild depression, making good progress.' },
    credentials: { username: 'arjun_mehta', passwordAutoGenerated: 'PHMS-3321', smsSent: true, emailSent: false },
    address: '45, Lake View Apartments, Jubilee Hills, Hyderabad - 500033',
    treatmentType: 'Advanced Pranic Healing',
    sessions: [],
    financials: { balanceDue: 0, invoices: [] },
    documents: [],
    appointments: [],
    activityLogs: [],
    statusHistory: [],
    healerHistory: [],
    feedback: [],
  },
  {
    id: 'PHX-2024-003',
    name: 'Kavita Patel',
    initials: 'KP',
    avatarColor: '#dc2626',
    mobile: '+91 76543 21098',
    email: 'kavita.patel@email.com',
    gender: 'Female',
    dateOfBirth: '1995-11-08',
    age: 28,
    bloodGroup: 'A-',
    occupation: 'Doctor',
    status: 'On Hold',
    assignedHealer: 'Dr. Anjali Rao',
    lastVisitDate: '2023-12-28',
    regDate: '2023-09-05',
    emergencyContact: { name: 'Vikram Patel', relation: 'Father', mobile: '+91 76666 33333' },
    medicalInfo: { conditions: ['Stress', 'Back Pain'], allergies: ['Dust'], medications: ['Vitamin D'], notes: 'Stress-related issues, on hold due to travel.' },
    credentials: { username: 'kavita_patel', passwordAutoGenerated: 'PHMS-7891', smsSent: false, emailSent: true },
    address: '89, Green Park Society, Madhapur, Hyderabad - 500081',
    treatmentType: 'Crystal Pranic Healing',
    sessions: [],
    financials: { balanceDue: 2500, invoices: [] },
    documents: [],
    appointments: [],
    activityLogs: [],
    statusHistory: [],
    healerHistory: [],
    feedback: [],
  },
];

// ─── Styles ───────────────────────────────────────────────────────────────────
const s = {
  card: {
    background: '#ffffff',
    borderRadius: '16px',
    padding: '28px',
    border: '1px solid #e2e8f0',
    boxShadow: '0 4px 6px -1px rgba(0,0,0,0.05)',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '20px',
  },
  sectionTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontSize: '16px',
    fontWeight: 700,
    color: 'var(--ba-color-primary)',
    marginBottom: '12px',
  },
  label: {
    display: 'block',
    fontSize: '11px',
    fontWeight: 800,
    color: '#475569',
    letterSpacing: '0.5px',
    marginBottom: '6px',
    textTransform: 'uppercase' as const,
  },
  input: {
    background: '#f8fafc',
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    padding: '11px 14px',
    fontSize: '14px',
    color: '#1e293b',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box' as const,
    transition: 'border-color 0.2s',
  },
  textarea: {
    background: '#f8fafc',
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    padding: '11px 14px',
    fontSize: '14px',
    color: '#1e293b',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box' as const,
    resize: 'none' as const,
    lineHeight: 1.6,
  },
  statusCard: (selected: boolean, color: string) => ({
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    padding: '16px 8px',
    borderRadius: '10px',
    cursor: 'pointer',
    textAlign: 'center' as const,
    transition: 'all 0.2s',
    border: selected ? `2px solid ${color}` : '1px solid #cbd5e1',
    background: selected ? `${color}18` : '#f8fafc',
    minHeight: '90px',
    justifyContent: 'center',
    gap: '6px',
  }),
};

// ─── Component ────────────────────────────────────────────────────────────────
export default function EditPatientPage() {
  const { id } = useParams<{ id: string }>();
  const history = useHistory();

  // Find patient by id from mock store
  const found = MOCK_PATIENTS.find((p) => p.id === decodeURIComponent(id));
  const [form, setForm] = useState<Patient | null>(found ?? null);
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    const p = MOCK_PATIENTS.find((p) => p.id === decodeURIComponent(id));
    if (p) setForm({ ...p });
  }, [id]);

  const goBack = () => history.push(ROUTES.BRANCH_ADMIN.PATIENTS);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    // In a real app: dispatch update action
    setSaved(true);
    setTimeout(() => {
      history.push(ROUTES.BRANCH_ADMIN.PATIENTS);
    }, 1200);
  };

  if (!form) {
    return (
      <IonPage>
        <IonContent>
          <div style={{ padding: '48px', textAlign: 'center', color: '#94a3b8' }}>
            <p style={{ fontSize: '18px' }}>Patient not found.</p>
            <button
              onClick={goBack}
              style={{ marginTop: '16px', padding: '10px 24px', background: 'var(--ba-color-primary)', color: '#fff', border: 'none', borderRadius: '8px', cursor: 'pointer', fontWeight: 600 }}
            >
              ← Back to Patients
            </button>
          </div>
        </IonContent>
      </IonPage>
    );
  }

  return (
    <IonPage>
      <IonContent style={{ '--background': '#f1f5f9' }}>
        <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '28px 24px 48px' }}>
          <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '28px' }}>

            {/* ── Header ── */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
              <button
                type="button"
                onClick={goBack}
                style={{
                  background: '#ffffff', border: '1px solid #cbd5e1', borderRadius: '8px',
                  width: '38px', height: '38px', display: 'flex', alignItems: 'center',
                  justifyContent: 'center', cursor: 'pointer', flexShrink: 0,
                }}
              >
                <IonIcon icon={arrowBackOutline} style={{ color: 'var(--ba-color-primary)', fontSize: '20px' }} />
              </button>
              <div>
                <h1 style={{ fontSize: '22px', fontWeight: 800, color: 'var(--ba-color-primary)', margin: 0, lineHeight: 1.2 }}>
                  Edit Patient Profile
                </h1>
                <p style={{ fontSize: '12px', color: '#64748b', margin: '3px 0 0 0' }}>
                  Modify identity, contact, address &amp; medical records &nbsp;•&nbsp; <strong>{form.id}</strong>
                </p>
              </div>

              {saved && (
                <div style={{
                  marginLeft: 'auto', background: '#dcfce7', border: '1px solid #a7f3d0',
                  borderRadius: '8px', padding: '8px 16px', fontSize: '13px', fontWeight: 600, color: '#047857',
                  display: 'flex', alignItems: 'center', gap: '6px',
                }}>
                  <IonIcon icon={checkmarkCircleOutline} />
                  Saved successfully!
                </div>
              )}
            </div>

            {/* ── 2-column grid ── */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '28px', alignItems: 'start' }}>

              {/* ── LEFT COLUMN ── */}
              <div style={{ display: 'flex', flexDirection: 'column', gap: '28px' }}>

                {/* Card: Patient Identity & Contact */}
                <div style={s.card}>

                  {/* Identity */}
                  <div>
                    <div style={s.sectionTitle}>
                      <IonIcon icon={personOutline} style={{ fontSize: '20px' }} />
                      Patient Identity
                    </div>

                    <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
                      <div>
                        <label style={s.label}>Full Name *</label>
                        <input
                          type="text"
                          style={s.input}
                          value={form.name}
                          onChange={(e) => setForm({ ...form, name: e.target.value })}
                          required
                          placeholder="Enter full name"
                        />
                      </div>

                      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px' }}>
                        <div>
                          <label style={s.label}>Gender</label>
                          <select style={s.input} value={form.gender} onChange={(e) => setForm({ ...form, gender: e.target.value as any })}>
                            <option value="Female">Female</option>
                            <option value="Male">Male</option>
                            <option value="Other">Other</option>
                          </select>
                        </div>
                        <div>
                          <label style={s.label}>Date of Birth</label>
                          <input
                            type="date"
                            style={s.input}
                            value={form.dateOfBirth || ''}
                            onChange={(e) => setForm({ ...form, dateOfBirth: e.target.value })}
                          />
                        </div>
                      </div>

                      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '14px' }}>
                        <div>
                          <label style={s.label}>Age</label>
                          <input
                            type="number"
                            style={s.input}
                            value={form.age}
                            min={0}
                            max={120}
                            onChange={(e) => setForm({ ...form, age: Number(e.target.value) })}
                            placeholder="e.g. 34"
                          />
                        </div>
                        <div>
                          <label style={s.label}>Blood Group</label>
                          <select style={s.input} value={form.bloodGroup} onChange={(e) => setForm({ ...form, bloodGroup: e.target.value })}>
                            {['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'].map((bg) => (
                              <option key={bg} value={bg}>{bg}</option>
                            ))}
                          </select>
                        </div>
                        <div>
                          <label style={s.label}>Occupation</label>
                          <input
                            type="text"
                            style={s.input}
                            value={form.occupation || ''}
                            onChange={(e) => setForm({ ...form, occupation: e.target.value })}
                            placeholder="e.g. Engineer"
                          />
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Contact */}
                  <div>
                    <div style={s.sectionTitle}>
                      <IonIcon icon={callOutline} style={{ fontSize: '20px' }} />
                      Contact Information
                    </div>

                    <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
                      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px' }}>
                        <div>
                          <label style={s.label}>Phone Number *</label>
                          <input
                            type="tel"
                            style={s.input}
                            value={form.mobile}
                            onChange={(e) => setForm({ ...form, mobile: e.target.value })}
                            required
                            placeholder="+91 XXXXX XXXXX"
                          />
                        </div>
                        <div>
                          <label style={s.label}>Email Address *</label>
                          <input
                            type="email"
                            style={s.input}
                            value={form.email}
                            onChange={(e) => setForm({ ...form, email: e.target.value })}
                            required
                            placeholder="email@example.com"
                          />
                        </div>
                      </div>

                      <div>
                        <label style={s.label}>Emergency Contact</label>
                        <input
                          type="text"
                          style={s.input}
                          value={form.emergencyContact?.name || ''}
                          onChange={(e) => setForm({
                            ...form,
                            emergencyContact: {
                              ...(form.emergencyContact || { name: '', relation: '', mobile: '' }),
                              name: e.target.value,
                            },
                          })}
                          placeholder="e.g. Husband Name — +91 XXXXX XXXXX"
                        />
                      </div>
                    </div>
                  </div>

                  {/* Address */}
                  <div>
                    <div style={s.sectionTitle}>
                      <IonIcon icon={locationOutline} style={{ fontSize: '20px' }} />
                      Address
                    </div>
                    <label style={s.label}>Residential / Communication Address</label>
                    <textarea
                      rows={3}
                      style={s.textarea}
                      value={form.address || ''}
                      onChange={(e) => setForm({ ...form, address: e.target.value })}
                      placeholder="Enter complete residential address including city and postal code"
                    />
                  </div>
                </div>

                {/* Card: Patient Status */}
                <div style={s.card}>
                  <div style={s.sectionTitle}>
                    <IonIcon icon={alertCircleOutline} style={{ fontSize: '20px' }} />
                    Patient Status
                  </div>

                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px' }}>
                    {[
                      { value: 'Active', label: 'Active', sub: 'Currently receiving healing', color: '#10b981', icon: checkmarkCircleOutline },
                      { value: 'On Hold', label: 'On Hold', sub: 'Temporarily paused', color: '#f59e0b', icon: swapHorizontalOutline },
                      { value: 'Completed', label: 'Completed', sub: 'Treatment successful', color: '#3b82f6', icon: checkmarkCircleOutline },
                      { value: 'Inactive', label: 'Inactive', sub: 'No longer in system', color: '#ef4444', icon: closeCircleOutline },
                    ].map(({ value, label, sub, color, icon }) => (
                      <div
                        key={value}
                        onClick={() => setForm({ ...form, status: value as any })}
                        style={s.statusCard(form.status === value, color)}
                      >
                        <IonIcon icon={icon} style={{ color, fontSize: '20px' }} />
                        <span style={{ fontWeight: 800, fontSize: '13px', color: form.status === value ? color : '#1e293b' }}>{label}</span>
                        <span style={{ fontSize: '11px', color: '#64748b', lineHeight: 1.3 }}>{sub}</span>
                      </div>
                    ))}
                  </div>
                </div>

              </div>

              {/* ── RIGHT COLUMN ── */}
              <div style={{ display: 'flex', flexDirection: 'column', gap: '28px' }}>

                {/* Card: Medical History & Allocation */}
                <div style={s.card}>
                  <div>
                    <div style={s.sectionTitle}>
                      <IonIcon icon={medkitOutline} style={{ fontSize: '20px' }} />
                      Medical History
                    </div>
                    <label style={s.label}>Conditions, Treatments &amp; Allergies</label>
                    <textarea
                      rows={4}
                      style={s.textarea}
                      value={form.medicalInfo?.notes || ''}
                      onChange={(e) => setForm({
                        ...form,
                        medicalInfo: {
                          ...(form.medicalInfo || { conditions: [], allergies: [], medications: [], notes: '' }),
                          notes: e.target.value,
                        },
                      })}
                      placeholder="Describe chronic conditions, allergies, medications, or prior healing experiences..."
                    />
                  </div>

                  <div>
                    <label style={s.label}>Assign Treatment Type</label>
                    <select
                      style={s.input}
                      value={form.treatmentType || 'Pranic Psychotherapy'}
                      onChange={(e) => setForm({ ...form, treatmentType: e.target.value })}
                    >
                      {['Pranic Psychotherapy', 'Advanced Pranic Healing', 'Crystal Pranic Healing', 'Basic Pranic Healing'].map((t) => (
                        <option key={t} value={t}>{t}</option>
                      ))}
                    </select>
                  </div>

                  <div>
                    <div style={s.sectionTitle}>
                      <IonIcon icon={peopleOutline} style={{ fontSize: '20px' }} />
                      Assigned Healer
                    </div>
                    <label style={s.label}>Responsible Healer</label>
                    <select
                      style={s.input}
                      value={form.assignedHealer}
                      onChange={(e) => setForm({ ...form, assignedHealer: e.target.value })}
                    >
                      <option value="None">None (Unassigned)</option>
                      <option value="Dr. Anjali Rao">Dr. Anjali Rao</option>
                      <option value="Dr. Kevin Smith">Dr. Kevin Smith</option>
                    </select>
                  </div>
                </div>

                {/* Card: Login Details */}
                <div style={s.card}>
                  <div style={s.sectionTitle}>
                    <IonIcon icon={shieldCheckmarkOutline} style={{ fontSize: '20px' }} />
                    Login Details
                  </div>

                  <div>
                    <label style={s.label}>Username</label>
                    <input
                      type="text"
                      style={s.input}
                      value={form.credentials?.username || form.name.toLowerCase().replace(/\s+/g, '_')}
                      onChange={(e) => setForm({
                        ...form,
                        credentials: {
                          ...(form.credentials || { username: '', passwordAutoGenerated: '', smsSent: true, emailSent: true }),
                          username: e.target.value,
                        },
                      })}
                      placeholder="e.g. priya_sharma"
                    />
                  </div>

                  <div>
                    <label style={s.label}>Password (Auto Generated)</label>
                    <div style={{ display: 'flex', gap: '10px' }}>
                      <input
                        type="text"
                        style={{ ...s.input, fontFamily: 'monospace', fontWeight: 'bold', letterSpacing: '1px' }}
                        value={form.credentials?.passwordAutoGenerated || 'PHMS-5542'}
                        onChange={(e) => setForm({
                          ...form,
                          credentials: {
                            ...(form.credentials || { username: '', passwordAutoGenerated: '', smsSent: true, emailSent: true }),
                            passwordAutoGenerated: e.target.value,
                          },
                        })}
                        placeholder="PHMS-XXXX"
                      />
                      <button
                        type="button"
                        onClick={() => {
                          const d = Math.floor(1000 + Math.random() * 9000);
                          setForm({
                            ...form,
                            credentials: {
                              ...(form.credentials || { username: '', passwordAutoGenerated: '', smsSent: true, emailSent: true }),
                              passwordAutoGenerated: `PHMS-${d}`,
                            },
                          });
                        }}
                        style={{
                          background: 'var(--ba-color-primary)', border: 'none', borderRadius: '8px',
                          padding: '0 16px', fontSize: '12px', fontWeight: 600, color: '#fff',
                          cursor: 'pointer', whiteSpace: 'nowrap',
                        }}
                      >
                        Regenerate
                      </button>
                    </div>
                  </div>

                  <div>
                    <label style={s.label}>Account Status</label>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', marginTop: '6px' }}>
                      {[
                        { v: 'Active', color: '#10b981' },
                        { v: 'Inactive', color: '#ef4444' },
                      ].map(({ v, color }) => (
                        <div
                          key={v}
                          onClick={() => setForm({ ...form, status: v as any })}
                          style={{
                            padding: '12px', borderRadius: '8px', cursor: 'pointer', textAlign: 'center',
                            fontWeight: 700, fontSize: '13px', transition: 'all 0.2s',
                            border: form.status === v ? `2px solid ${color}` : '1px solid #cbd5e1',
                            background: form.status === v ? `${color}18` : '#f8fafc',
                            color: form.status === v ? color : '#475569',
                          }}
                        >
                          {v}
                        </div>
                      ))}
                    </div>
                  </div>
                </div>

                {/* Card: Uploaded Documents */}
                <div style={s.card}>
                  <div style={s.sectionTitle}>
                    <IonIcon icon={documentTextOutline} style={{ fontSize: '20px' }} />
                    Uploaded Documents
                  </div>

                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                    {/* Medical Reports — shows existing */}
                    <div>
                      <label style={s.label}>Medical Reports</label>
                      <div style={{
                        background: '#f0fdf4', border: '1px solid #a7f3d0', borderRadius: '8px',
                        height: '40px', display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                        padding: '0 12px',
                      }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '6px', overflow: 'hidden' }}>
                          <IonIcon icon={checkmarkCircleOutline} style={{ color: '#10b981', flexShrink: 0 }} />
                          <span style={{ fontSize: '11px', color: '#065f46', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                            Blood_Work_Oct.pdf
                          </span>
                        </div>
                        <IonIcon icon={trashOutline} style={{ color: '#ef4444', fontSize: '14px', cursor: 'pointer', flexShrink: 0 }} />
                      </div>
                    </div>

                    {/* Lab Results — upload */}
                    <div>
                      <label style={s.label}>Lab Results</label>
                      <label style={{
                        background: '#f8fafc', border: '1px dashed #cbd5e1', borderRadius: '8px',
                        height: '40px', display: 'flex', alignItems: 'center', justifyContent: 'center',
                        cursor: 'pointer',
                      }}>
                        <IonIcon icon={cloudUploadOutline} style={{ color: '#94a3b8', fontSize: '18px' }} />
                        <input type="file" style={{ display: 'none' }} />
                      </label>
                    </div>
                  </div>
                </div>

              </div>
            </div>

            {/* ── Footer Actions ── */}
            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '14px', paddingTop: '4px' }}>
              <button
                type="button"
                onClick={goBack}
                style={{
                  background: '#ffffff', border: '1px solid #cbd5e1', borderRadius: '8px',
                  padding: '10px 26px', fontSize: '14px', fontWeight: 600, color: '#475569',
                  cursor: 'pointer', transition: 'all 0.2s',
                }}
              >
                Cancel
              </button>
              <button
                type="submit"
                style={{
                  background: 'var(--ba-color-primary)', border: 'none', borderRadius: '8px',
                  padding: '10px 30px', fontSize: '14px', fontWeight: 600, color: '#ffffff',
                  cursor: 'pointer', transition: 'all 0.2s',
                }}
              >
                Save Record
              </button>
            </div>

          </form>
        </div>
      </IonContent>
    </IonPage>
  );
}
