import React, { useState, useEffect } from 'react';
import {
  IonPage,
  IonContent,
  IonIcon,
} from '@ionic/react';
import {
  arrowBackOutline,
  personOutline,
  callOutline,
  locationOutline,
  alertCircleOutline,
  medkitOutline,
  peopleOutline,
  documentTextOutline,
  cloudUploadOutline,
  checkmarkCircleOutline,
  trashOutline,
  shieldCheckmarkOutline,
} from 'ionicons/icons';
import { useHistory, useParams } from 'react-router-dom';
import { useAuthStore } from '../../store/auth.store';
import { ROUTES } from '../../constants/routes.constant';
import { Patient } from './PatientsPage';
import './branch-admin.css';

// Mock Patients store to locate the patient being edited
const MOCK_PATIENTS: Patient[] = [
  {
    id: '#P-8921',
    name: 'Sarah Mitchell',
    initials: 'SM',
    avatarColor: '#0f5b4b',
    mobile: '9876543210',
    email: 'sarah.m@example.com',
    gender: 'Female',
    age: 34,
    bloodGroup: 'O+',
    dateOfBirth: '1990-03-15',
    occupation: 'Marketing Executive',
    assignedHealer: 'Dr. Anjali Rao',
    regDate: '2023-10-12',
    lastVisitDate: '2024-05-20',
    status: 'Active',
    emergencyContact: {
      name: 'Mark Mitchell',
      relation: 'Husband',
      mobile: '9876543299',
    },
    medicalInfo: {
      conditions: ['Lower Back Pain (L4-L5 Compression)', 'Migraines'],
      allergies: ['Lavender Aromatherapy oil', 'Penicillin'],
      medications: ['Energetic alignment sessions thrice weekly', 'Hydration logs'],
      notes: 'Hyper-sensitive to strong aromatherapy. Standard aura cleansing highly recommended.',
    },
    appointments: [
      { id: '#APT-401', date: '2024-05-28', time: '10:30 AM', healer: 'Dr. Anjali Rao', status: 'Confirmed', remindersEnabled: true },
      { id: '#APT-201', date: '2024-05-20', time: '09:15 AM', healer: 'Dr. Anjali Rao', status: 'Completed', remindersEnabled: true },
      { id: '#APT-101', date: '2024-05-02', time: '03:30 PM', healer: 'Dr. Kevin Smith', status: 'Cancelled', remindersEnabled: false },
    ],
    sessions: [
      { id: '#SES-301', healer: 'Dr. Anjali Rao', status: 'Completed', notes: 'Chakra balancing focused on root and solar plexus. Blockages cleared.', followUpDate: '2024-05-28' },
      { id: '#SES-401', healer: 'Dr. Anjali Rao', status: 'Scheduled', notes: 'Pranic psychotherapy session focused on emotional aura release.', followUpDate: '2024-06-05' },
    ],
    financials: {
      balanceDue: 2500,
      invoices: [
        { id: '#INV-9021', date: '2024-05-20', amount: 1500, status: 'Paid', method: 'UPI' },
        { id: '#INV-9022', date: '2024-05-28', amount: 2500, status: 'Unpaid' },
      ],
    },
    documents: [
      { id: '#DOC-001', name: 'Blood_Work_Oct.pdf', category: 'Lab Report', size: '2.4 MB', date: '2023-10-14', type: 'pdf', uploadedBy: 'Dr. Anjali Rao' },
      { id: '#DOC-002', name: 'Scan_Result_Chest.jpg', category: 'Doctor Report', size: '5.1 MB', date: '2023-10-12', type: 'image', uploadedBy: 'Dr. Anjali Rao' },
    ],
    activityLogs: [
      { action: 'Session #SES-301 completed by Healer Anjali', timestamp: '2 hours ago', category: 'session_update' },
      { action: 'Emergency contact information updated', timestamp: 'Yesterday', category: 'profile_update' },
      { action: 'UPI Payment of ₹1,500 recorded for invoice #INV-9021', timestamp: '3 days ago', category: 'payment' },
      { action: 'User authenticated via security login node', timestamp: 'May 20, 08:30 AM', category: 'login' },
    ],
    statusHistory: [
      { prevStatus: 'None', newStatus: 'Active', changedBy: 'System Registry', timestamp: '2023-10-12 09:00:00' }
    ],
    healerHistory: [
      { prevHealer: 'None', newHealer: 'Dr. Anjali Rao', changedBy: 'System Registry', timestamp: '2023-10-12 09:05:00' }
    ],
    feedback: [
      { sessionRef: '#SES-301', rating: 5, comment: 'Incredible mental relief! The anxiety completely melted away.', date: '2024-05-20' }
    ],
    credentials: {
      username: 'sarah_mitchell',
      passwordAutoGenerated: 'PHMS-u9#2b',
      smsSent: true,
      emailSent: true
    },
    address: '12 Rose Garden Colony, Banjara Hills, Hyderabad, Telangana - 500034',
    treatmentType: 'Pranic Psychotherapy',
  },
  {
    id: '#P-8922',
    name: 'John Walker',
    initials: 'JW',
    avatarColor: '#1e3a8a',
    mobile: '9911223344',
    email: 'john.walker@example.com',
    gender: 'Male',
    age: 45,
    bloodGroup: 'A-',
    dateOfBirth: '1979-05-20',
    occupation: 'Business Consultant',
    assignedHealer: 'Dr. Kevin Smith',
    regDate: '2023-10-15',
    lastVisitDate: '2024-05-22',
    status: 'Active',
    emergencyContact: {
      name: 'Jane Walker',
      relation: 'Sister',
      mobile: '9911223399',
    },
    medicalInfo: {
      conditions: ['Osteoarthritis of Right Knee', 'Hypertension'],
      allergies: ['Patchouli incense', 'Sulfonamides'],
      medications: ['Joint alignment alignment', 'Pranic salt baths'],
      notes: 'Avoid burning heavy patchouli or frankincense incense resins in his presence.',
    },
    appointments: [
      { id: '#APT-402', date: '2024-06-02', time: '11:30 AM', healer: 'Dr. Kevin Smith', status: 'Pending', remindersEnabled: true },
      { id: '#APT-202', date: '2024-05-22', time: '02:00 PM', healer: 'Dr. Kevin Smith', status: 'Completed', remindersEnabled: true },
    ],
    sessions: [
      { id: '#SES-302', healer: 'Dr. Kevin Smith', status: 'Completed', notes: 'Cleansing energy flows around knee joint, reducing heat and local inflammation.', followUpDate: '2024-06-02' },
    ],
    financials: {
      balanceDue: 0,
      invoices: [
        { id: '#INV-9023', date: '2024-05-22', amount: 1200, status: 'Paid', method: 'Cash' },
      ],
    },
    documents: [
      { id: '#DOC-003', name: 'Knee_XRay_Report.pdf', category: 'Doctor Report', size: '3.2 MB', date: '2023-10-16', type: 'pdf', uploadedBy: 'Dr. Kevin Smith' },
    ],
    activityLogs: [
      { action: 'Session #SES-302 completed by Healer Kevin', timestamp: '3 days ago', category: 'session_update' },
      { action: 'Cash Payment of ₹1,200 recorded for invoice #INV-9023', timestamp: '3 days ago', category: 'payment' },
      { action: 'User authenticated via security login node', timestamp: 'May 22, 09:10 AM', category: 'login' },
    ],
    statusHistory: [
      { prevStatus: 'None', newStatus: 'Active', changedBy: 'System Registry', timestamp: '2023-10-15 10:00:00' }
    ],
    healerHistory: [
      { prevHealer: 'None', newHealer: 'Dr. Kevin Smith', changedBy: 'System Registry', timestamp: '2023-10-15 10:10:00' }
    ],
    feedback: [
      { sessionRef: '#SES-302', rating: 4, comment: 'Knee pain is much lower today. Feeling the heat release.', date: '2024-05-22' }
    ],
    credentials: {
      username: 'john_walker',
      passwordAutoGenerated: 'PHMS-v8#3z',
      smsSent: true,
      emailSent: true
    },
    address: '45 Lake View Apartments, Jubilee Hills, Hyderabad, Telangana - 500033',
    treatmentType: 'Advanced Pranic Healing',
  },
  {
    id: '#P-8923',
    name: 'Elena Rostova',
    initials: 'ER',
    avatarColor: '#b45309',
    mobile: '9876543211',
    email: 'elena.rostova@example.com',
    gender: 'Female',
    age: 28,
    bloodGroup: 'B+',
    dateOfBirth: '1996-08-12',
    occupation: 'Artist',
    assignedHealer: 'Dr. Anjali Rao',
    regDate: '2023-10-18',
    lastVisitDate: '2024-05-25',
    status: 'Inactive',
    emergencyContact: {
      name: 'Dmitri Rostov',
      relation: 'Father',
      mobile: '9876543200',
    },
    medicalInfo: {
      conditions: ['Generalized Anxiety Disorder (GAD)', 'Insomnia'],
      allergies: ['No known environmental allergies'],
      medications: ['Emotional cleansing', 'Crown chakra alignments'],
      notes: 'Responds highly to solar plexus energizing and crown chakra emotional sweeps.',
    },
    appointments: [
      { id: '#APT-203', date: '2024-05-25', time: '05:00 PM', healer: 'Dr. Anjali Rao', status: 'Completed', remindersEnabled: true },
    ],
    sessions: [
      { id: '#SES-303', healer: 'Dr. Anjali Rao', status: 'Completed', notes: 'Psychotherapy session. Calming energy infused into nervous system. Emotional seal applied.', followUpDate: '2024-06-10' },
    ],
    financials: {
      balanceDue: 0,
      invoices: [
        { id: '#INV-9024', date: '2024-05-25', amount: 1800, status: 'Paid', method: 'Card' },
      ],
    },
    documents: [
      { id: '#DOC-004', name: 'Anxiety_Scale_Oct.pdf', category: 'Consultation Note', size: '1.8 MB', date: '2023-10-20', type: 'pdf', uploadedBy: 'Dr. Anjali Rao' },
    ],
    activityLogs: [
      { action: 'Psychotherapy session #SES-303 closed successfully', timestamp: '5 hours ago', category: 'session_update' },
      { action: 'Registered at Salem Branch node', timestamp: 'Salem Node • Oct 18', category: 'profile_update' },
      { action: 'User authenticated via security login node', timestamp: 'May 25, 11:40 AM', category: 'login' },
    ],
    statusHistory: [
      { prevStatus: 'None', newStatus: 'Inactive', changedBy: 'System Registry', timestamp: '2023-10-18 11:00:00' }
    ],
    healerHistory: [
      { prevHealer: 'None', newHealer: 'Dr. Anjali Rao', changedBy: 'System Registry', timestamp: '2023-10-18 11:15:00' }
    ],
    feedback: [
      { sessionRef: '#SES-303', rating: 5, comment: 'The psychological aura release was extremely intense but helpful.', date: '2024-05-25' }
    ],
    credentials: {
      username: 'elena_rostova',
      passwordAutoGenerated: 'PHMS-t6#7y',
      smsSent: true,
      emailSent: true
    },
    address: '89 Green Park Society, Madhapur, Hyderabad, Telangana - 500081',
    treatmentType: 'Pranic Psychotherapy',
  },
];

export default function EditPatientPages() {
  const { id } = useParams<{ id: string }>();
  const history = useHistory();
  const { user } = useAuthStore();
  const isBranchAdmin = user?.role === 'BRANCH_ADMIN';

  // Current Date display
  const formattedDate = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  // Form states matching RegisterPatientPage form fields
  const [formData, setFormData] = useState({
    name: '',
    mobile: '',
    email: '',
    gender: 'Female' as 'Male' | 'Female' | 'Other',
    dateOfBirth: '',
    age: '',
    bloodGroup: 'O+',
    occupation: '',
    emergencyContact: '',
    address: '',
    addressLine1: '',
    addressLine2: '',
    city: '',
    state: '',
    pincode: '',
    status: 'Active' as 'Active' | 'On Hold' | 'Completed' | 'Inactive',
    medicalHistory: '',
    treatmentType: 'Pranic Psychotherapy',
    assignedHealer: 'Dr. Aris Varma',
    username: '',
    password: '',
    accountStatus: 'Active' as 'Active' | 'Inactive',
  });

  // Uploaded files mock state
  const [uploadedFiles, setUploadedFiles] = useState<{ [key: string]: { name: string; size: string } | null }>({
    reports: { name: 'Blood_Work_Oct.pdf', size: '1.20 MB' },
    labResults: null,
    prescriptions: null,
    scanImages: null,
    consultationNotes: null,
    idProofs: null,
    healingRecords: null,
  });

  const [showSuccessToast, setShowSuccessToast] = useState(false);
  const [savedPatientId, setSavedPatientId] = useState('');

  // Load patient data and parse the address
  useEffect(() => {
    const p = MOCK_PATIENTS.find((p) => p.id === decodeURIComponent(id));
    if (p) {
      let line1 = p.address || '';
      let line2 = '';
      let city = '';
      let state = '';
      let pin = '';
      
      const parts = line1.split(',').map(part => part.trim());
      if (parts.length >= 3) {
        const lastPart = parts.pop() || '';
        const statePinParts = lastPart.split('-').map(part => part.trim());
        if (statePinParts.length === 2) {
          pin = statePinParts[1];
          state = statePinParts[0];
        } else {
          state = lastPart;
        }
        
        if (parts.length >= 1) {
          city = parts.pop() || '';
        }
        
        if (parts.length >= 1) {
          line2 = parts.pop() || '';
        }
        
        line1 = parts.join(', ');
      }
      
      setFormData({
        name: p.name,
        mobile: p.mobile,
        email: p.email,
        gender: p.gender || 'Female',
        dateOfBirth: p.dateOfBirth || '',
        age: p.age ? String(p.age) : '',
        bloodGroup: p.bloodGroup || 'O+',
        occupation: p.occupation || '',
        emergencyContact: p.emergencyContact?.name || '',
        address: p.address || '',
        addressLine1: line1 || p.address || '',
        addressLine2: line2 || '',
        city: city || 'Hyderabad',
        state: state || 'Telangana',
        pincode: pin || '500034',
        status: p.status || 'Active',
        medicalHistory: p.medicalInfo?.notes || '',
        treatmentType: p.treatmentType || 'Pranic Psychotherapy',
        assignedHealer: p.assignedHealer || 'Dr. Anjali Rao',
        username: p.credentials?.username || '',
        password: p.credentials?.passwordAutoGenerated || 'PHMS-5542',
        accountStatus: p.status === 'Inactive' ? 'Inactive' : 'Active',
      });
    }
  }, [id]);

  // Handle Input Changes
  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  // Simulate File Upload
  const handleFileChange = (field: string, e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      const file = e.target.files[0];
      const sizeMB = (file.size / (1024 * 1024)).toFixed(2);
      setUploadedFiles((prev) => ({
        ...prev,
        [field]: { name: file.name, size: `${sizeMB} MB` },
      }));
    }
  };

  // Clear Uploaded File
  const handleClearFile = (field: string, e: React.MouseEvent) => {
    e.stopPropagation();
    setUploadedFiles((prev) => ({
      ...prev,
      [field]: null,
    }));
  };

  const handleClearForm = () => {
    setFormData({
      name: '',
      mobile: '',
      email: '',
      gender: 'Female',
      dateOfBirth: '',
      age: '',
      bloodGroup: 'O+',
      occupation: '',
      emergencyContact: '',
      address: '',
      addressLine1: '',
      addressLine2: '',
      city: '',
      state: '',
      pincode: '',
      status: 'Active',
      medicalHistory: '',
      treatmentType: 'Pranic Psychotherapy',
      assignedHealer: 'Dr. Aris Varma',
      username: '',
      password: '',
      accountStatus: 'Active',
    });
    setUploadedFiles({
      reports: null,
      labResults: null,
      prescriptions: null,
      scanImages: null,
      consultationNotes: null,
      idProofs: null,
      healingRecords: null,
    });
  };

  const handleRegeneratePassword = () => {
    const randomDigits = Math.floor(1000 + Math.random() * 9000);
    setFormData((prev) => ({
      ...prev,
      password: `PHMS-${randomDigits}`,
    }));
  };

  // Handle Submit
  const handleSaveRecord = (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.name.trim()) {
      alert('Patient Full Name is required.');
      return;
    }
    if (!formData.mobile.trim()) {
      alert('Phone Number is required.');
      return;
    }
    if (!formData.email.trim() || !formData.email.includes('@')) {
      alert('A valid email address is required.');
      return;
    }

    // Combine address components
    const fullAddress = [
      formData.addressLine1.trim(),
      formData.addressLine2.trim(),
      formData.city.trim(),
      formData.state.trim(),
    ].filter(Boolean).join(', ') + (formData.pincode.trim() ? ` - ${formData.pincode.trim()}` : '');
    
    formData.address = fullAddress;

    setSavedPatientId(decodeURIComponent(id));
    setShowSuccessToast(true);
  };

  const closeAndRedirect = () => {
    setShowSuccessToast(false);
    history.push(ROUTES.BRANCH_ADMIN.PATIENTS);
  };

  if (!isBranchAdmin) {
    return (
      <IonPage className="sa-page">
        <IonContent className="sa-page__content" fullscreen>
          <div className="db-access-restricted-container">
            <div className="db-access-restricted-card">
              <div className="db-access-restricted-icon">
                <IonIcon icon={alertCircleOutline} />
              </div>
              <div className="db-access-restricted-details">
                <span className="db-access-restricted-title">Unauthorized Access</span>
                <p className="db-access-restricted-desc">
                  Access Denied. Patient profile editing is restricted to authorized Branch Admin users.
                </p>
              </div>
            </div>
          </div>
        </IonContent>
      </IonPage>
    );
  }

  // Custom CSS Style Blocks matching the registration page style
  const customStyles = {
    formCard: {
      background: '#ffffff',
      borderRadius: '16px',
      padding: '28px',
      border: '1px solid #e2e8f0',
      boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.025)',
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '24px',
    },
    subHeader: {
      display: 'flex',
      alignItems: 'center',
      gap: '10px',
      fontSize: '18px',
      fontWeight: 700,
      color: '#0D5C46',
      marginTop: '8px',
      marginBottom: '16px',
    },
    subHeaderIcon: {
      color: '#0D5C46',
      fontSize: '22px',
    },
    label: {
      fontSize: '11px',
      fontWeight: 800,
      color: '#475569',
      letterSpacing: '0.5px',
      marginBottom: '6px',
      textTransform: 'uppercase' as const,
    },
    grayInput: {
      background: '#f8fafc',
      border: '1px solid #e2e8f0',
      borderRadius: '8px',
      padding: '12px 16px',
      fontSize: '14px',
      color: '#1e293b',
      outline: 'none',
      width: '100%',
      transition: 'all 0.2s ease',
    },
    grayTextarea: {
      background: '#f8fafc',
      border: '1px solid #e2e8f0',
      borderRadius: '8px',
      padding: '12px 16px',
      fontSize: '14px',
      color: '#1e293b',
      outline: 'none',
      width: '100%',
      resize: 'none' as const,
      lineHeight: 1.5,
      transition: 'all 0.2s ease',
    },
    dashedUpload: {
      background: '#f8fafc',
      border: '1px dashed #cbd5e1',
      borderRadius: '8px',
      height: '38px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      cursor: 'pointer',
      width: '100%',
      transition: 'all 0.2s ease',
      position: 'relative' as const,
    },
    dashedUploadActive: {
      background: '#f0fdf4',
      border: '1px solid #a7f3d0',
      borderRadius: '8px',
      height: '38px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '0 12px',
      cursor: 'pointer',
      width: '100%',
    },
  };

  return (
    <IonPage className="sa-page">
      <IonContent className="sa-page__content" style={{ '--background': '#f8fafc' }} fullscreen>
        <div className="db-corp-layout" style={{ background: '#f8fafc' }}>
          
          <main className="db-corp-canvas">
            {/* Horizontal Header Navbar */}
            <header className="db-corp-navbar" style={{ background: '#ffffff', borderBottom: '1px solid #e2e8f0', padding: '16px 24px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                <button className="db-corp-nav-icon-btn" onClick={() => history.push(ROUTES.BRANCH_ADMIN.PATIENTS)} title="Back to Patients">
                  <IonIcon icon={arrowBackOutline} style={{ color: '#0D5C46', fontSize: '20px' }} />
                </button>
                <div className="db-corp-navbar-left">
                  <h1 className="db-corp-page-title" style={{ color: '#0d5c46', fontWeight: 800 }}>Edit Patient Profile</h1>
                  <p className="db-corp-page-subtitle">Pranic Healing Management System • {formattedDate}</p>
                </div>
              </div>
            </header>

            {/* Main Form Workspace Area */}
            <div className="db-hc-layout" style={{ padding: '28px' }}>
              
              <form onSubmit={handleSaveRecord} style={{ display: 'flex', flexDirection: 'column', gap: '28px' }}>
                
                {/* 2-Column Grid Layout */}
                <div style={{ display: 'grid', gridTemplateColumns: '1.2fr 1fr', gap: '28px', alignItems: 'start' }}>
                  
                  {/* LEFT COLUMN: Identity, Contact, Address, Status */}
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '28px' }}>
                    
                    {/* Card 1: Patient Identity & Contact Info */}
                    <div style={customStyles.formCard}>
                      
                      {/* Section 1: Patient Identity */}
                      <div>
                        <div style={customStyles.subHeader}>
                          <IonIcon icon={personOutline} style={customStyles.subHeaderIcon} />
                          <span>Patient Identity</span>
                        </div>
                        <div className="st-form-group">
                          <label style={customStyles.label}>PATIENT FULL NAME</label>
                          <input 
                            type="text" 
                            name="name" 
                            style={customStyles.grayInput}
                            value={formData.name} 
                            onChange={handleInputChange} 
                            required 
                            placeholder="Enter Name"
                          />
                        </div>

                        {/* Gender & Date of Birth row */}
                        <div className="st-form-row" style={{ marginTop: '16px' }}>
                          <div className="st-form-group">
                            <label style={customStyles.label}>GENDER</label>
                            <select
                              name="gender"
                              style={customStyles.grayInput}
                              value={formData.gender}
                              onChange={handleInputChange}
                            >
                              <option value="">Select Gender</option>
                              <option value="Female">Female</option>
                              <option value="Male">Male</option>
                              <option value="Other">Other</option>
                            </select>
                          </div>
                          <div className="st-form-group">
                            <label style={customStyles.label}>DATE OF BIRTH</label>
                            <input
                              type="date"
                              name="dateOfBirth"
                              style={customStyles.grayInput}
                              value={formData.dateOfBirth}
                              onChange={handleInputChange}
                            />
                          </div>
                        </div>

                        {/* Age, Blood Group & Occupation row */}
                        <div className="st-form-row" style={{ marginTop: '16px' }}>
                          <div className="st-form-group">
                            <label style={customStyles.label}>AGE</label>
                            <input
                              type="number"
                              name="age"
                              style={customStyles.grayInput}
                              value={formData.age}
                              onChange={handleInputChange}
                              placeholder="Enter age in years"
                              min="0"
                              max="120"
                            />
                          </div>
                          <div className="st-form-group">
                            <label style={customStyles.label}>BLOOD GROUP</label>
                            <select
                              name="bloodGroup"
                              style={customStyles.grayInput}
                              value={formData.bloodGroup}
                              onChange={handleInputChange}
                            >
                              <option value="">Select Blood Group</option>
                              <option value="A+">A+</option>
                              <option value="A-">A-</option>
                              <option value="B+">B+</option>
                              <option value="B-">B-</option>
                              <option value="AB+">AB+</option>
                              <option value="AB-">AB-</option>
                              <option value="O+">O+</option>
                              <option value="O-">O-</option>
                            </select>
                          </div>
                          <div className="st-form-group">
                            <label style={customStyles.label}>OCCUPATION</label>
                            <input
                              type="text"
                              name="occupation"
                              style={customStyles.grayInput}
                              value={formData.occupation}
                              onChange={handleInputChange}
                              placeholder="Enter occupation (e.g. Engineer)"
                            />
                          </div>
                        </div>
                      </div>

                      {/* Section 2: Contact Information */}
                      <div>
                        <div style={customStyles.subHeader}>
                          <IonIcon icon={callOutline} style={customStyles.subHeaderIcon} />
                          <span>Contact Information</span>
                        </div>
                        
                        <div className="st-form-row" style={{ marginBottom: '16px' }}>
                          <div className="st-form-group">
                            <label style={customStyles.label}>PHONE NUMBER</label>
                            <input 
                              type="tel" 
                              name="mobile" 
                              style={customStyles.grayInput}
                              value={formData.mobile} 
                              onChange={handleInputChange} 
                              required 
                              placeholder="Enter mobile number"
                            />
                          </div>

                          <div className="st-form-group">
                            <label style={customStyles.label}>EMAIL ADDRESS</label>
                            <input 
                              type="email" 
                              name="email" 
                              style={customStyles.grayInput}
                              value={formData.email} 
                              onChange={handleInputChange} 
                              required 
                              placeholder="Enter email address"
                            />
                          </div>
                        </div>

                        <div className="st-form-group">
                          <label style={customStyles.label}>EMERGENCY CONTACT DETAILS</label>
                          <input 
                            type="text" 
                            name="emergencyContact" 
                            style={customStyles.grayInput}
                            value={formData.emergencyContact} 
                            onChange={handleInputChange} 
                            placeholder="e.g Husband number"
                          />
                        </div>
                      </div>

                      {/* Section 3: Address */}
                      <div>
                        <div style={customStyles.subHeader}>
                          <IonIcon icon={locationOutline} style={customStyles.subHeaderIcon} />
                          <span>Address Details</span>
                        </div>
                        
                        {/* Address Line 1 */}
                        <div className="st-form-group">
                          <label style={customStyles.label}>Address Line 1 *</label>
                          <input 
                            type="text" 
                            name="addressLine1" 
                            style={customStyles.grayInput}
                            value={formData.addressLine1} 
                            onChange={handleInputChange} 
                            placeholder="Building, Flat, Street name"
                            required 
                          />
                        </div>

                        {/* Address Line 2 */}
                        <div className="st-form-group" style={{ marginTop: '16px' }}>
                          <label style={customStyles.label}>Address Line 2</label>
                          <input 
                            type="text" 
                            name="addressLine2" 
                            style={customStyles.grayInput}
                            value={formData.addressLine2} 
                            onChange={handleInputChange} 
                            placeholder="Landmark, Area, Locality (Optional)"
                          />
                        </div>

                        {/* City, State & Pincode Row */}
                        <div className="st-form-row" style={{ marginTop: '16px', display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '16px' }}>
                          <div className="st-form-group">
                            <label style={customStyles.label}>City *</label>
                            <input 
                              type="text" 
                              name="city" 
                              style={customStyles.grayInput}
                              value={formData.city} 
                              onChange={handleInputChange} 
                              placeholder="City"
                              required 
                            />
                          </div>

                          <div className="st-form-group">
                            <label style={customStyles.label}>State *</label>
                            <input 
                              type="text" 
                              name="state" 
                              style={customStyles.grayInput}
                              value={formData.state} 
                              onChange={handleInputChange} 
                              placeholder="State"
                              required 
                            />
                          </div>

                          <div className="st-form-group">
                            <label style={customStyles.label}>Pincode *</label>
                            <input 
                              type="text" 
                              name="pincode" 
                              style={customStyles.grayInput}
                              value={formData.pincode} 
                              onChange={handleInputChange} 
                              placeholder="6-digit Pincode"
                              pattern="[0-9]{6}"
                              required 
                            />
                          </div>
                        </div>
                      </div>

                    </div>
                  </div>

                  {/* RIGHT COLUMN: Medical History, Assigned Healer, Uploaded Documents */}
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '28px', width: '100%' }}>
                    
                    {/* Card 1: Medical History & Allocation */}
                    <div style={customStyles.formCard}>
                      
                      {/* Section 1: Medical History */}
                      <div>
                        <div style={customStyles.subHeader}>
                          <IonIcon icon={medkitOutline} style={customStyles.subHeaderIcon} />
                          <span>Medical History</span>
                        </div>
                        <div className="st-form-group">
                          <label style={customStyles.label}>CONDITIONS, TREATMENTS &amp; ALLERGIES</label>
                          <textarea 
                            name="medicalHistory" 
                            rows={4} 
                            style={customStyles.grayTextarea}
                            value={formData.medicalHistory} 
                            onChange={handleInputChange} 
                            placeholder="Describe any chronic conditions, allergies, current medications, or previous energy healing experiences..."
                          />
                        </div>
                      </div>

                      {/* Section 2: Allocation */}
                      <div className="st-form-group" style={{ marginTop: '8px' }}>
                        <label style={customStyles.label}>ASSIGN TREATMENT TYPE</label>
                        <select name="treatmentType" className="st-input" style={customStyles.grayInput} value={formData.treatmentType} onChange={handleInputChange}>
                          <option value="">Select Treatment Type</option>
                          <option value="Pranic Psychotherapy">Pranic Psychotherapy</option>
                          <option value="Advanced Pranic Healing">Advanced Pranic Healing</option>
                          <option value="Crystal Pranic Healing">Crystal Pranic Healing</option>
                          <option value="Basic Pranic Healing">Basic Pranic Healing</option>
                        </select>
                      </div>

                      {/* Section 3: Assigned Healer */}
                      <div>
                        <div style={customStyles.subHeader}>
                          <IonIcon icon={peopleOutline} style={customStyles.subHeaderIcon} />
                          <span>Assigned Healer</span>
                        </div>
                        <div className="st-form-group">
                          <label style={customStyles.label}>RESPONSIBLE HEALER</label>
                          <select name="assignedHealer" className="st-input" style={customStyles.grayInput} value={formData.assignedHealer} onChange={handleInputChange}>
                            <option value="">Select Healer</option>
                            <option value="Dr. Aris Varma">Dr. Aris Varma</option>
                            <option value="Dr. Anjali Rao">Dr. Anjali Rao</option>
                            <option value="Dr. Kevin Smith">Dr. Kevin Smith</option>
                          </select>
                        </div>
                      </div>
                    </div>

                    {/* Card 2: Login Details */}
                    <div style={customStyles.formCard}>
                      <div style={customStyles.subHeader}>
                        <IonIcon icon={shieldCheckmarkOutline} style={customStyles.subHeaderIcon} />
                        <span>Login Details</span>
                      </div>

                      <div className="st-form-group">
                        <label style={customStyles.label}>USERNAME</label>
                        <input 
                          type="text" 
                          name="username" 
                          style={customStyles.grayInput}
                          value={formData.username} 
                          onChange={handleInputChange} 
                          placeholder="e.g. dr._aris varma"
                          required
                        />
                      </div>

                      <div className="st-form-group">
                        <label style={customStyles.label}>PASSWORD</label>
                        <div style={{ display: 'flex', gap: '12px' }}>
                          <input 
                            type="text" 
                            name="password" 
                            style={{ ...customStyles.grayInput, fontFamily: 'monospace', fontWeight: 'bold' }}
                            value={formData.password} 
                            onChange={handleInputChange} 
                            placeholder="PHMS-XXXX"
                            required
                          />
                          <button 
                            type="button"
                            onClick={handleRegeneratePassword}
                            style={{
                              background: '#0D5C46',
                              border: 'none',
                              borderRadius: '8px',
                              padding: '10px 16px',
                              fontSize: '12px',
                              fontWeight: 600,
                              color: '#ffffff',
                              cursor: 'pointer',
                              whiteSpace: 'nowrap',
                              transition: 'background 0.2s ease',
                            }}
                          >
                            Regenerate
                          </button>
                        </div>
                      </div>

                      <div>
                        <label style={customStyles.label}>ACCOUNT STATUS</label>
                        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', marginTop: '6px' }}>
                          {/* Active */}
                          <div 
                            onClick={() => setFormData(prev => ({ ...prev, accountStatus: 'Active', status: 'Active' }))}
                            style={{
                              padding: '12px',
                              borderRadius: '8px',
                              border: formData.accountStatus === 'Active' ? '2px solid #10b981' : '1px solid #cbd5e1',
                              background: formData.accountStatus === 'Active' ? '#f0fdf4' : '#f8fafc',
                              cursor: 'pointer',
                              textAlign: 'center',
                              fontWeight: 700,
                              fontSize: '13px',
                              color: formData.accountStatus === 'Active' ? '#047857' : '#475569',
                              transition: 'all 0.2s ease'
                            }}
                          >
                            Active
                          </div>

                          {/* Inactive */}
                          <div 
                            onClick={() => setFormData(prev => ({ ...prev, accountStatus: 'Inactive', status: 'Inactive' }))}
                            style={{
                              padding: '12px',
                              borderRadius: '8px',
                              border: formData.accountStatus === 'Inactive' ? '2px solid #ef4444' : '1px solid #cbd5e1',
                              background: formData.accountStatus === 'Inactive' ? '#fef2f2' : '#f8fafc',
                              cursor: 'pointer',
                              textAlign: 'center',
                              fontWeight: 700,
                              fontSize: '13px',
                              color: formData.accountStatus === 'Inactive' ? '#b91c1c' : '#475569',
                              transition: 'all 0.2s ease'
                            }}
                          >
                            Inactive
                          </div>
                        </div>
                      </div>
                    </div>

                  </div>
                </div>

                {/* Full-Width: Uploaded Documents */}
                <div style={customStyles.formCard}>
                  <div style={customStyles.subHeader}>
                    <IonIcon icon={documentTextOutline} style={customStyles.subHeaderIcon} />
                    <span>Uploaded Documents</span>
                  </div>

                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: '20px' }}>
                    {/* Medical Reports */}
                    <div className="st-form-group">
                      <label style={customStyles.label}>Medical Reports</label>
                      {uploadedFiles.reports ? (
                        <div style={customStyles.dashedUploadActive}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '6px', width: '80%' }}>
                            <IonIcon icon={checkmarkCircleOutline} style={{ color: '#10b981' }} />
                            <span style={{ fontSize: '11px', color: '#065f46', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                              {uploadedFiles.reports.name}
                            </span>
                          </div>
                          <IonIcon icon={trashOutline} onClick={(e) => handleClearFile('reports', e)} style={{ color: '#ef4444', fontSize: '14px' }} />
                        </div>
                      ) : (
                        <label style={customStyles.dashedUpload}>
                          <IonIcon icon={cloudUploadOutline} style={{ color: '#94a3b8', fontSize: '18px' }} />
                          <input type="file" style={{ display: 'none' }} onChange={(e) => handleFileChange('reports', e)} />
                        </label>
                      )}
                    </div>

                    {/* Lab Results */}
                    <div className="st-form-group">
                      <label style={customStyles.label}>Lab Results</label>
                      {uploadedFiles.labResults ? (
                        <div style={customStyles.dashedUploadActive}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '6px', width: '80%' }}>
                            <IonIcon icon={checkmarkCircleOutline} style={{ color: '#10b981' }} />
                            <span style={{ fontSize: '11px', color: '#065f46', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                              {uploadedFiles.labResults.name}
                            </span>
                          </div>
                          <IonIcon icon={trashOutline} onClick={(e) => handleClearFile('labResults', e)} style={{ color: '#ef4444', fontSize: '14px' }} />
                        </div>
                      ) : (
                        <label style={customStyles.dashedUpload}>
                          <IonIcon icon={cloudUploadOutline} style={{ color: '#94a3b8', fontSize: '18px' }} />
                          <input type="file" style={{ display: 'none' }} onChange={(e) => handleFileChange('labResults', e)} />
                        </label>
                      )}
                    </div>

                    {/* Prescriptions */}
                    <div className="st-form-group">
                      <label style={customStyles.label}>Prescriptions</label>
                      {uploadedFiles.prescriptions ? (
                        <div style={customStyles.dashedUploadActive}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '6px', width: '80%' }}>
                            <IonIcon icon={checkmarkCircleOutline} style={{ color: '#10b981' }} />
                            <span style={{ fontSize: '11px', color: '#065f46', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                              {uploadedFiles.prescriptions.name}
                            </span>
                          </div>
                          <IonIcon icon={trashOutline} onClick={(e) => handleClearFile('prescriptions', e)} style={{ color: '#ef4444', fontSize: '14px' }} />
                        </div>
                      ) : (
                        <label style={customStyles.dashedUpload}>
                          <IonIcon icon={cloudUploadOutline} style={{ color: '#94a3b8', fontSize: '18px' }} />
                          <input type="file" style={{ display: 'none' }} onChange={(e) => handleFileChange('prescriptions', e)} />
                        </label>
                      )}
                    </div>

                    {/* Scan Images */}
                    <div className="st-form-group">
                      <label style={customStyles.label}>Scan Images</label>
                      {uploadedFiles.scanImages ? (
                        <div style={customStyles.dashedUploadActive}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '6px', width: '80%' }}>
                            <IonIcon icon={checkmarkCircleOutline} style={{ color: '#10b981' }} />
                            <span style={{ fontSize: '11px', color: '#065f46', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                              {uploadedFiles.scanImages.name}
                            </span>
                          </div>
                          <IonIcon icon={trashOutline} onClick={(e) => handleClearFile('scanImages', e)} style={{ color: '#ef4444', fontSize: '14px' }} />
                        </div>
                      ) : (
                        <label style={customStyles.dashedUpload}>
                          <IonIcon icon={cloudUploadOutline} style={{ color: '#94a3b8', fontSize: '18px' }} />
                          <input type="file" style={{ display: 'none' }} onChange={(e) => handleFileChange('scanImages', e)} />
                        </label>
                      )}
                    </div>

                    {/* Consultation Notes */}
                    <div className="st-form-group">
                      <label style={customStyles.label}>Consultation Notes</label>
                      {uploadedFiles.consultationNotes ? (
                        <div style={customStyles.dashedUploadActive}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '6px', width: '80%' }}>
                            <IonIcon icon={checkmarkCircleOutline} style={{ color: '#10b981' }} />
                            <span style={{ fontSize: '11px', color: '#065f46', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                              {uploadedFiles.consultationNotes.name}
                            </span>
                          </div>
                          <IonIcon icon={trashOutline} onClick={(e) => handleClearFile('consultationNotes', e)} style={{ color: '#ef4444', fontSize: '14px' }} />
                        </div>
                      ) : (
                        <label style={customStyles.dashedUpload}>
                          <IonIcon icon={cloudUploadOutline} style={{ color: '#94a3b8', fontSize: '18px' }} />
                          <input type="file" style={{ display: 'none' }} onChange={(e) => handleFileChange('consultationNotes', e)} />
                        </label>
                      )}
                    </div>

                    {/* ID Proofs */}
                    <div className="st-form-group">
                      <label style={customStyles.label}>ID Proofs</label>
                      {uploadedFiles.idProofs ? (
                        <div style={customStyles.dashedUploadActive}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '6px', width: '80%' }}>
                            <IonIcon icon={checkmarkCircleOutline} style={{ color: '#10b981' }} />
                            <span style={{ fontSize: '11px', color: '#065f46', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                              {uploadedFiles.idProofs.name}
                            </span>
                          </div>
                          <IonIcon icon={trashOutline} onClick={(e) => handleClearFile('idProofs', e)} style={{ color: '#ef4444', fontSize: '14px' }} />
                        </div>
                      ) : (
                        <label style={customStyles.dashedUpload}>
                          <IonIcon icon={cloudUploadOutline} style={{ color: '#94a3b8', fontSize: '18px' }} />
                          <input type="file" style={{ display: 'none' }} onChange={(e) => handleFileChange('idProofs', e)} />
                        </label>
                      )}
                    </div>

                    {/* Healing Records */}
                    <div className="st-form-group">
                      <label style={customStyles.label}>Healing Records</label>
                      {uploadedFiles.healingRecords ? (
                        <div style={customStyles.dashedUploadActive}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '6px', width: '80%' }}>
                            <IonIcon icon={checkmarkCircleOutline} style={{ color: '#10b981' }} />
                            <span style={{ fontSize: '11px', color: '#065f46', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                              {uploadedFiles.healingRecords.name}
                            </span>
                          </div>
                          <IonIcon icon={trashOutline} onClick={(e) => handleClearFile('healingRecords', e)} style={{ color: '#ef4444', fontSize: '14px' }} />
                        </div>
                      ) : (
                        <label style={customStyles.dashedUpload}>
                          <IonIcon icon={cloudUploadOutline} style={{ color: '#94a3b8', fontSize: '18px' }} />
                          <input type="file" style={{ display: 'none' }} onChange={(e) => handleFileChange('healingRecords', e)} />
                        </label>
                      )}
                    </div>
                  </div>
                </div>

                {/* Bottom Footer Actions block */}
                <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '16px', marginTop: '12px', marginBottom: '28px' }}>
                  <button 
                    type="button" 
                    onClick={handleClearForm} 
                    style={{
                      background: '#ffffff',
                      border: '1px solid #cbd5e1',
                      borderRadius: '8px',
                      padding: '10px 24px',
                      fontSize: '14px',
                      fontWeight: 600,
                      color: '#ef4444',
                      cursor: 'pointer',
                      transition: 'all 0.2s ease',
                      marginRight: 'auto',
                    }}
                  >
                    Clear Form
                  </button>

                  <button 
                    type="button" 
                    onClick={() => history.push(ROUTES.BRANCH_ADMIN.PATIENTS)} 
                    style={{
                      background: '#ffffff',
                      border: '1px solid #cbd5e1',
                      borderRadius: '8px',
                      padding: '10px 24px',
                      fontSize: '14px',
                      fontWeight: 600,
                      color: '#475569',
                      cursor: 'pointer',
                      transition: 'all 0.2s ease',
                    }}
                  >
                    Cancel
                  </button>

                  <button 
                    type="submit" 
                    style={{
                      background: '#0D5C46',
                      border: 'none',
                      borderRadius: '8px',
                      padding: '10px 28px',
                      fontSize: '14px',
                      fontWeight: 600,
                      color: '#ffffff',
                      cursor: 'pointer',
                      transition: 'all 0.2s ease',
                    }}
                  >
                    Save Changes
                  </button>
                </div>

              </form>
            </div>
          </main>
        </div>

        {/* Success Modal */}
        {showSuccessToast && (
          <div style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, zIndex: 9999, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(15,23,42,0.6)', backdropFilter: 'blur(4px)' }}>
            <div className="db-corp-card" style={{ maxWidth: '420px', width: '90%', padding: '32px', textAlign: 'center', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '16px', animation: 'scaleUp 0.3s ease-out' }}>
              <div style={{ width: '64px', height: '64px', borderRadius: '50%', background: '#ecfdf5', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <IonIcon icon={checkmarkCircleOutline} style={{ color: '#10b981', fontSize: '40px' }} />
              </div>
              <div>
                <h3 style={{ fontSize: '18px', fontWeight: '800', color: '#1e293b', margin: '0 0 6px 0' }}>Patient Updated Successfully</h3>
                <p style={{ fontSize: '13px', color: '#64748b', margin: '0', lineHeight: 1.5 }}>
                  Profile updates for <strong>{formData.name}</strong> have been successfully saved.
                </p>
              </div>
              
              <div style={{ background: '#f8fafc', border: '1px solid #e2e8f0', padding: '10px 16px', borderRadius: '8px', fontSize: '13px', width: '100%' }}>
                <span style={{ color: '#64748b', fontWeight: 600 }}>SYSTEM RECORD ID:</span>
                <strong style={{ color: '#0D5C46', display: 'block', fontSize: '15px', marginTop: '2px', fontFamily: 'monospace' }}>{savedPatientId}</strong>
              </div>

              <button onClick={closeAndRedirect} className="sa-btn sa-btn--primary" style={{ width: '100%', justifyContent: 'center', margin: 0 }}>
                Proceed to Patient Registry
              </button>
            </div>
          </div>
        )}
      </IonContent>
    </IonPage>
  );
}
