import React, { useState, useEffect } from 'react';
import {
  IonPage,
  IonContent,
  IonHeader,
  IonToolbar,
  IonButtons,
  IonMenuButton,
  IonIcon,
  IonModal,
} from '@ionic/react';
import {
  notificationsOutline,
  helpCircleOutline,
  searchOutline,
  filterOutline,
  calendarOutline,
  eyeOutline,
  pencilOutline,
  checkmarkCircleOutline,
  timeOutline,
  documentTextOutline,
  imageOutline,
  alertCircleOutline,
  flagOutline,
  trendingUpOutline,
  downloadOutline,
  printOutline,
  addOutline,
  chevronForwardOutline,
  star,
  mailOutline,
  callOutline,
  waterOutline,
  trashOutline,
  cashOutline,
  personOutline,
  cloudUploadOutline,
  closeOutline,
  shieldCheckmarkOutline,
  swapHorizontalOutline,
  barChartOutline,
  receiptOutline,
  settingsOutline,
  arrowBackOutline,
  locationOutline,
  medkitOutline,
  peopleOutline,
  closeCircleOutline,
} from 'ionicons/icons';
import { useHistory } from 'react-router-dom';
import { useAuthStore } from '../../store/auth.store';
import { ROUTES } from '../../constants/routes.constant';
import './branch-admin.css';
import DetailsPatientPage from './DetailsPatientPage';

// Highly comprehensive Patient structure matching all requirements
export interface Patient {
  id: string; // Patient ID
  name: string; // Patient Name
  photoUrl?: string; // Profile Photo Mock
  initials: string;
  avatarColor: string;
  mobile: string; // Mobile Number
  email: string; // Email Address
  gender: 'Male' | 'Female'; // Gender
  age: number; // Age
  bloodGroup: string; // Blood Group
  dateOfBirth: string; // Date of Birth
  occupation: string; // Occupation
  assignedHealer: string; // Assigned Healer
  regDate: string; // Registration Date
  lastVisitDate: string; // Last Visit Date
  status: 'Active' | 'On Hold' | 'Completed' | 'Inactive'; // Status
  address?: string;
  treatmentType?: string;
  emergencyContact: {
    name: string;
    relation: string;
    mobile: string;
  };
  medicalInfo: {
    conditions: string[];
    allergies: string[];
    medications: string[];
    notes: string;
  };
  appointments: {
    id: string;
    date: string;
    time: string;
    healer: string;
    status: 'Pending' | 'Confirmed' | 'Completed' | 'Cancelled' | 'Rescheduled';
    remindersEnabled: boolean;
  }[];
  sessions: {
    id: string;
    healer: string;
    status: 'Scheduled' | 'Ongoing' | 'Completed' | 'Cancelled';
    notes: string;
    followUpDate?: string;
  }[];
  financials: {
    balanceDue: number;
    invoices: {
      id: string;
      date: string;
      amount: number;
      status: 'Paid' | 'Unpaid' | 'Partial';
      method?: 'Cash' | 'UPI' | 'Card' | 'Bank Transfer';
    }[];
  };
  documents: {
    id: string;
    name: string;
    category: 'Doctor Report' | 'Lab Report' | 'Consultation Note' | 'Other';
    size: string;
    date: string;
    type: 'pdf' | 'image';
    uploadedBy: string;
  }[];
  activityLogs: {
    action: string;
    timestamp: string;
    category: 'login' | 'appointment' | 'payment' | 'profile_update' | 'session_update';
  }[];
  statusHistory: {
    prevStatus: string;
    newStatus: string;
    changedBy: string;
    timestamp: string;
  }[];
  healerHistory: {
    prevHealer: string;
    newHealer: string;
    changedBy: string;
    timestamp: string;
  }[];
  feedback: {
    sessionRef: string;
    rating: number;
    comment: string;
    date: string;
  }[];
  credentials?: {
    username: string;
    passwordAutoGenerated: string;
    smsSent: boolean;
    emailSent: boolean;
  };
}

const PatientsPage: React.FC = () => {
  const { user } = useAuthStore();
  const history = useHistory();

  // Strict Scoping / Access Control Check
  const isBranchAdmin = user?.role === 'BRANCH_ADMIN';

  const customStyles = {
    formCard: {
      background: '#ffffff',
      borderRadius: '16px',
      padding: '28px',
      border: '1px solid #e2e8f0',
      boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.025)',
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '20px',
    },
    subHeader: {
      display: 'flex',
      alignItems: 'center',
      gap: '10px',
      fontSize: '18px',
      fontWeight: 700,
      color: 'var(--ba-color-primary)',
      marginTop: '4px',
      marginBottom: '12px',
    },
    subHeaderIcon: {
      color: 'var(--ba-color-primary)',
      fontSize: '22px',
    },
    label: {
      fontSize: '11px',
      fontWeight: 800,
      color: '#475569',
      letterSpacing: '0.5px',
      marginBottom: '6px',
      textTransform: 'uppercase' as const,
    },
    grayInput: {
      background: '#f8fafc',
      border: '1px solid #e2e8f0',
      borderRadius: '8px',
      padding: '12px 16px',
      fontSize: '14px',
      color: '#1e293b',
      outline: 'none',
      width: '100%',
      transition: 'all 0.2s ease',
    },
    grayTextarea: {
      background: '#f8fafc',
      border: '1px solid #e2e8f0',
      borderRadius: '8px',
      padding: '12px 16px',
      fontSize: '14px',
      color: '#1e293b',
      outline: 'none',
      width: '100%',
      resize: 'none' as const,
      lineHeight: 1.5,
      transition: 'all 0.2s ease',
    },
    dashedUpload: {
      background: '#f8fafc',
      border: '1px dashed #cbd5e1',
      borderRadius: '8px',
      height: '38px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      cursor: 'pointer',
      width: '100%',
      transition: 'all 0.2s ease',
    },
    dashedUploadActive: {
      background: '#f0fdf4',
      border: '1px solid #a7f3d0',
      borderRadius: '8px',
      height: '38px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '0 12px',
      cursor: 'pointer',
      width: '100%',
    },
    statusCard: {
      display: 'flex',
      flexDirection: 'column' as const,
      alignItems: 'center',
      justifyContent: 'center',
      padding: '20px 12px',
      borderRadius: '12px',
      cursor: 'pointer',
      textAlign: 'center' as const,
      transition: 'all 0.2s ease',
      width: '100%',
      minHeight: '104px',
    },
  };

  // Primary State
  const [patients, setPatients] = useState<Patient[]>([
    {
      id: '#P-8921',
      name: 'Sarah Mitchell',
      initials: 'SM',
      avatarColor: '#0f5b4b',
      mobile: '9876543210',
      email: 'sarah.m@example.com',
      gender: 'Female',
      age: 34,
      bloodGroup: 'O+',
      dateOfBirth: '',
      occupation: '',
      assignedHealer: 'Dr. Anjali Rao',
      regDate: '2023-10-12',
      lastVisitDate: '2024-05-20',
      status: 'Active',
      emergencyContact: {
        name: 'Mark Mitchell',
        relation: 'Husband',
        mobile: '9876543299',
      },
      medicalInfo: {
        conditions: ['Lower Back Pain (L4-L5 Compression)', 'Migraines'],
        allergies: ['Lavender Aromatherapy oil', 'Penicillin'],
        medications: ['Energetic alignment sessions thrice weekly', 'Hydration logs'],
        notes: 'Hyper-sensitive to strong aromatherapy. Standard aura cleansing highly recommended.',
      },
      appointments: [
        { id: '#APT-401', date: '2024-05-28', time: '10:30 AM', healer: 'Dr. Anjali Rao', status: 'Confirmed', remindersEnabled: true },
        { id: '#APT-201', date: '2024-05-20', time: '09:15 AM', healer: 'Dr. Anjali Rao', status: 'Completed', remindersEnabled: true },
        { id: '#APT-101', date: '2024-05-02', time: '03:30 PM', healer: 'Dr. Kevin Smith', status: 'Cancelled', remindersEnabled: false },
      ],
      sessions: [
        { id: '#SES-301', healer: 'Dr. Anjali Rao', status: 'Completed', notes: 'Chakra balancing focused on root and solar plexus. Blockages cleared.', followUpDate: '2024-05-28' },
        { id: '#SES-401', healer: 'Dr. Anjali Rao', status: 'Scheduled', notes: 'Pranic psychotherapy session focused on emotional aura release.', followUpDate: '2024-06-05' },
      ],
      financials: {
        balanceDue: 2500,
        invoices: [
          { id: '#INV-9021', date: '2024-05-20', amount: 1500, status: 'Paid', method: 'UPI' },
          { id: '#INV-9022', date: '2024-05-28', amount: 2500, status: 'Unpaid' },
        ],
      },
      documents: [
        { id: '#DOC-001', name: 'Blood_Work_Oct.pdf', category: 'Lab Report', size: '2.4 MB', date: '2023-10-14', type: 'pdf', uploadedBy: 'Dr. Anjali Rao' },
        { id: '#DOC-002', name: 'Scan_Result_Chest.jpg', category: 'Doctor Report', size: '5.1 MB', date: '2023-10-12', type: 'image', uploadedBy: 'Dr. Anjali Rao' },
      ],
      activityLogs: [
        { action: 'Session #SES-301 completed by Healer Anjali', timestamp: '2 hours ago', category: 'session_update' },
        { action: 'Emergency contact information updated', timestamp: 'Yesterday', category: 'profile_update' },
        { action: 'UPI Payment of ₹1,500 recorded for invoice #INV-9021', timestamp: '3 days ago', category: 'payment' },
        { action: 'User authenticated via security login node', timestamp: 'May 20, 08:30 AM', category: 'login' },
      ],
      statusHistory: [
        { prevStatus: 'None', newStatus: 'Active', changedBy: 'System Registry', timestamp: '2023-10-12 09:00:00' }
      ],
      healerHistory: [
        { prevHealer: 'None', newHealer: 'Dr. Anjali Rao', changedBy: 'System Registry', timestamp: '2023-10-12 09:05:00' }
      ],
      feedback: [
        { sessionRef: '#SES-301', rating: 5, comment: 'Incredible mental relief! The anxiety completely melted away.', date: '2024-05-20' }
      ],
      credentials: {
        username: 'sarah_mitchell',
        passwordAutoGenerated: 'PHMS-u9#2b',
        smsSent: true,
        emailSent: true
      }
    },
    {
      id: '#P-8922',
      name: 'John Walker',
      initials: 'JW',
      avatarColor: '#1e3a8a',
      mobile: '9911223344',
      email: 'john.walker@example.com',
      gender: 'Male',
      age: 45,
      bloodGroup: 'A-',
      dateOfBirth: '',
      occupation: '',
      assignedHealer: 'Dr. Kevin Smith',
      regDate: '2023-10-15',
      lastVisitDate: '2024-05-22',
      status: 'Active',
      emergencyContact: {
        name: 'Jane Walker',
        relation: 'Sister',
        mobile: '9911223399',
      },
      medicalInfo: {
        conditions: ['Osteoarthritis of Right Knee', 'Hypertension'],
        allergies: ['Patchouli incense', 'Sulfonamides'],
        medications: ['Joint alignment alignment', 'Pranic salt baths'],
        notes: 'Avoid burning heavy patchouli or frankincense incense resins in his presence.',
      },
      appointments: [
        { id: '#APT-402', date: '2024-06-02', time: '11:30 AM', healer: 'Dr. Kevin Smith', status: 'Pending', remindersEnabled: true },
        { id: '#APT-202', date: '2024-05-22', time: '02:00 PM', healer: 'Dr. Kevin Smith', status: 'Completed', remindersEnabled: true },
      ],
      sessions: [
        { id: '#SES-302', healer: 'Dr. Kevin Smith', status: 'Completed', notes: 'Cleansing energy flows around knee joint, reducing heat and local inflammation.', followUpDate: '2024-06-02' },
      ],
      financials: {
        balanceDue: 0,
        invoices: [
          { id: '#INV-9023', date: '2024-05-22', amount: 1200, status: 'Paid', method: 'Cash' },
        ],
      },
      documents: [
        { id: '#DOC-003', name: 'Knee_XRay_Report.pdf', category: 'Doctor Report', size: '3.2 MB', date: '2023-10-16', type: 'pdf', uploadedBy: 'Dr. Kevin Smith' },
      ],
      activityLogs: [
        { action: 'Session #SES-302 completed by Healer Kevin', timestamp: '3 days ago', category: 'session_update' },
        { action: 'Cash Payment of ₹1,200 recorded for invoice #INV-9023', timestamp: '3 days ago', category: 'payment' },
        { action: 'User authenticated via security login node', timestamp: 'May 22, 09:10 AM', category: 'login' },
      ],
      statusHistory: [
        { prevStatus: 'None', newStatus: 'Active', changedBy: 'System Registry', timestamp: '2023-10-15 10:00:00' }
      ],
      healerHistory: [
        { prevHealer: 'None', newHealer: 'Dr. Kevin Smith', changedBy: 'System Registry', timestamp: '2023-10-15 10:10:00' }
      ],
      feedback: [
        { sessionRef: '#SES-302', rating: 4, comment: 'Knee pain is much lower today. Feeling the heat release.', date: '2024-05-22' }
      ],
      credentials: {
        username: 'john_walker',
        passwordAutoGenerated: 'PHMS-v8#3z',
        smsSent: true,
        emailSent: true
      }
    },
    {
      id: '#P-8923',
      name: 'Elena Rostova',
      initials: 'ER',
      avatarColor: '#b45309',
      mobile: '9876543211',
      email: 'elena.rostova@example.com',
      gender: 'Female',
      age: 28,
      bloodGroup: 'B+',
      dateOfBirth: '',
      occupation: '',
      assignedHealer: 'Dr. Anjali Rao',
      regDate: '2023-10-18',
      lastVisitDate: '2024-05-25',
      status: 'Inactive',
      emergencyContact: {
        name: 'Dmitri Rostov',
        relation: 'Father',
        mobile: '9876543200',
      },
      medicalInfo: {
        conditions: ['Generalized Anxiety Disorder (GAD)', 'Insomnia'],
        allergies: ['No known environmental allergies'],
        medications: ['Emotional cleansing', 'Crown chakra alignments'],
        notes: 'Responds highly to solar plexus energizing and crown chakra emotional sweeps.',
      },
      appointments: [
        { id: '#APT-203', date: '2024-05-25', time: '05:00 PM', healer: 'Dr. Anjali Rao', status: 'Completed', remindersEnabled: true },
      ],
      sessions: [
        { id: '#SES-303', healer: 'Dr. Anjali Rao', status: 'Completed', notes: 'Psychotherapy session. Calming energy infused into nervous system. Emotional seal applied.', followUpDate: '2024-06-10' },
      ],
      financials: {
        balanceDue: 0,
        invoices: [
          { id: '#INV-9024', date: '2024-05-25', amount: 1800, status: 'Paid', method: 'Card' },
        ],
      },
      documents: [
        { id: '#DOC-004', name: 'Anxiety_Scale_Oct.pdf', category: 'Consultation Note', size: '1.8 MB', date: '2023-10-20', type: 'pdf', uploadedBy: 'Dr. Anjali Rao' },
      ],
      activityLogs: [
        { action: 'Psychotherapy session #SES-303 closed successfully', timestamp: '5 hours ago', category: 'session_update' },
        { action: 'Registered at Salem Branch node', timestamp: 'Salem Node • Oct 18', category: 'profile_update' },
        { action: 'User authenticated via security login node', timestamp: 'May 25, 11:40 AM', category: 'login' },
      ],
      statusHistory: [
        { prevStatus: 'None', newStatus: 'Inactive', changedBy: 'System Registry', timestamp: '2023-10-18 11:00:00' }
      ],
      healerHistory: [
        { prevHealer: 'None', newHealer: 'Dr. Anjali Rao', changedBy: 'System Registry', timestamp: '2023-10-18 11:15:00' }
      ],
      feedback: [
        { sessionRef: '#SES-303', rating: 5, comment: 'The psychological aura release was extremely intense but helpful.', date: '2024-05-25' }
      ],
      credentials: {
        username: 'elena_rostova',
        passwordAutoGenerated: 'PHMS-t6#7y',
        smsSent: true,
        emailSent: true
      }
    },
  ]);

  // Selected Patient Workspace
  const [selectedPatientId, setSelectedPatientId] = useState<string>('#P-8921');
  const [viewMode, setViewMode] = useState<'list' | 'detail' | 'edit'>('list');

  // Search & Filter & Sorting state
  const [searchQuery, setSearchQuery] = useState('');
  const [genderFilter, setGenderFilter] = useState('All');
  const [statusFilter, setStatusFilter] = useState('All');
  const [healerFilter, setHealerFilter] = useState('All');
  const [sortBy, setSortBy] = useState('Newest');

  // Modals state
  const [showAddModal, setShowAddModal] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);

  // Form states
  const [newPatient, setNewPatient] = useState({
    name: '',
    mobile: '',
    email: '',
    gender: 'Female' as 'Male' | 'Female',
    age: 30,
    bloodGroup: 'O+',
    dateOfBirth: '',
    occupation: '',
    assignedHealer: 'None',
    emergencyName: '',
    emergencyRelation: '',
    emergencyMobile: '',
    conditions: '',
    allergies: '',
    notes: '',
  });

  const [editForm, setEditForm] = useState<Patient | null>(null);

  // Branch Name details
  const userName = user?.name || `${user?.firstName || ''} ${user?.lastName || ''}`.trim() || 'Aria Seraphina';
  const nameParts = userName.split(' ');
  const displayName = nameParts.length > 1 ? `${nameParts[0]} ${nameParts[1][0]}.` : userName;
  const userInitials = user
    ? `${user.name?.[0] || user.firstName?.[0] || 'B'}${user.name?.split(' ')?.[1]?.[0] || user.lastName?.[0] || 'A'}`.toUpperCase()
    : 'BA';

  const rawBranch = typeof user?.branch === 'object' && user?.branch !== null
    ? (user.branch as any).name
    : (user?.branch || 'Mumbai');
  const branchName = rawBranch.toLowerCase().includes('branch') ? rawBranch : `${rawBranch} Branch`;

  // Filter & Sort Logic
  const filteredPatients = patients.filter((p) => {
    const matchesSearch =
      p.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      p.mobile.includes(searchQuery) ||
      p.id.toLowerCase().includes(searchQuery.toLowerCase()) ||
      p.email.toLowerCase().includes(searchQuery.toLowerCase());

    const matchesGender = genderFilter === 'All' || p.gender === genderFilter;
    const matchesStatus = statusFilter === 'All' || p.status === statusFilter;
    const matchesHealer = healerFilter === 'All' || p.assignedHealer === healerFilter;

    return matchesSearch && matchesGender && matchesStatus && matchesHealer;
  });

  const sortedPatients = [...filteredPatients].sort((a, b) => {
    if (sortBy === 'Newest') {
      return new Date(b.regDate).getTime() - new Date(a.regDate).getTime();
    }
    if (sortBy === 'Alphabetical') {
      return a.name.localeCompare(b.name);
    }
    if (sortBy === 'Recent Visit') {
      return new Date(b.lastVisitDate).getTime() - new Date(a.lastVisitDate).getTime();
    }
    if (sortBy === 'Reg Date') {
      return new Date(a.regDate).getTime() - new Date(b.regDate).getTime();
    }
    return 0;
  });

  const selectedPatient = patients.find((p) => p.id === selectedPatientId) || patients[0];

  useEffect(() => {
    if (selectedPatient) {
      setEditForm({ ...selectedPatient });
    }
  }, [selectedPatientId, viewMode, patients]);

  if (!isBranchAdmin) {
    return (
      <IonPage className="sa-page">
        <IonContent className="sa-page__content" fullscreen>
          <div className="db-access-restricted-container">
            <div className="db-access-restricted-card">
              <div className="db-access-restricted-icon">
                <IonIcon icon={alertCircleOutline} />
              </div>
              <div className="db-access-restricted-details">
                <span className="db-access-restricted-title">Unauthorized Node Access</span>
                <p className="db-access-restricted-desc">
                  Access Denied. The Patient Management workspace is restricted exclusively to authorized Branch Admin users. You do not possess the required credentials to access this branch data.
                </p>
              </div>
            </div>
          </div>
        </IonContent>
      </IonPage>
    );
  }

  // Handle Add Patient Action
  const handleAddPatientSubmit = () => {
    if (!newPatient.name || !newPatient.mobile || !newPatient.email) {
      alert('Please fill in required fields.');
      return;
    }

    const patientId = `#P-${Math.floor(1000 + Math.random() * 9000)}`;
    const hasHealer = newPatient.assignedHealer && newPatient.assignedHealer !== 'None';
    const username = newPatient.name.toLowerCase().replace(/\s+/g, '_') + `_${Math.floor(Math.random() * 100)}`;
    const passwordAutoGenerated = `PHMS-${Math.random().toString(36).substring(2, 7)}#`;
    const credentials = hasHealer ? {
      username,
      passwordAutoGenerated,
      smsSent: true,
      emailSent: true
    } : undefined;

    const timestampString = new Date().toISOString().replace('T', ' ').substring(0, 19);

    const initialActivityLogs = [
      { action: 'Patient registered folder initialized', timestamp: 'Just now', category: 'profile_update' as const },
    ];
    if (hasHealer) {
      initialActivityLogs.unshift(
        { action: `SMS login credentials dispatched for username: ${username}`, timestamp: 'Just now', category: 'profile_update' as const },
        { action: `Email login credentials dispatched for email: ${newPatient.email}`, timestamp: 'Just now', category: 'profile_update' as const }
      );
    }

    const added: Patient = {
      id: patientId,
      name: newPatient.name,
      initials: newPatient.name.split(' ').map((n) => n[0]).join('').slice(0, 2).toUpperCase(),
      avatarColor: ['#0f5b4b', '#1e3a8a', '#b45309', '#7c3aed', '#db2777'][Math.floor(Math.random() * 5)],
      mobile: newPatient.mobile,
      email: newPatient.email,
      gender: newPatient.gender,
      age: Number(newPatient.age),
      bloodGroup: newPatient.bloodGroup,
      dateOfBirth: newPatient.dateOfBirth,
      occupation: newPatient.occupation,
      assignedHealer: newPatient.assignedHealer,
      regDate: new Date().toISOString().split('T')[0],
      lastVisitDate: new Date().toISOString().split('T')[0],
      status: 'Active',
      emergencyContact: {
        name: newPatient.emergencyName || 'Emergency Name',
        relation: newPatient.emergencyRelation || 'Family',
        mobile: newPatient.emergencyMobile || '9876543210',
      },
      medicalInfo: {
        conditions: newPatient.conditions ? newPatient.conditions.split(',').map((c) => c.trim()) : ['None recorded'],
        allergies: newPatient.allergies ? newPatient.allergies.split(',').map((c) => c.trim()) : ['No known allergies'],
        medications: ['Pranic treatment protocols'],
        notes: newPatient.notes || 'No specialized clinical notes entered.',
      },
      appointments: [],
      sessions: [],
      financials: { balanceDue: 0, invoices: [] },
      documents: [],
      activityLogs: initialActivityLogs,
      statusHistory: [
        { prevStatus: 'None', newStatus: 'Active', changedBy: displayName, timestamp: timestampString }
      ],
      healerHistory: [
        { prevHealer: 'None', newHealer: newPatient.assignedHealer, changedBy: displayName, timestamp: timestampString }
      ],
      feedback: [],
      credentials,
    };

    setPatients([added, ...patients]);
    setSelectedPatientId(patientId);
    setNewPatient({
      name: '',
      mobile: '',
      email: '',
      gender: 'Female',
      age: 30,
      bloodGroup: 'O+',
      dateOfBirth: '',
      occupation: '',
      assignedHealer: 'None',
      emergencyName: '',
      emergencyRelation: '',
      emergencyMobile: '',
      conditions: '',
      allergies: '',
      notes: '',
    });
    setShowAddModal(false);
  };

  // Handle Edit Patient Action
  const handleEditPatientSubmit = (updatedPatient?: Patient) => {
    const patientToSave = updatedPatient || editForm;
    if (!patientToSave) return;
    const oldPatient = patients.find((p) => p.id === patientToSave.id) || selectedPatient;
    const timestampString = new Date().toISOString().replace('T', ' ').substring(0, 19);

    let updatedHealerHistory = [...(patientToSave.healerHistory || [])];
    let updatedStatusHistory = [...(patientToSave.statusHistory || [])];
    let updatedActivityLogs = [...(patientToSave.activityLogs || [])];
    let credentials = patientToSave.credentials;

    // Detect healer change
    if (patientToSave.assignedHealer !== oldPatient.assignedHealer) {
      updatedHealerHistory.unshift({
        prevHealer: oldPatient.assignedHealer || 'None',
        newHealer: patientToSave.assignedHealer,
        changedBy: displayName,
        timestamp: timestampString,
      });
      updatedActivityLogs.unshift({
        action: `Healer assignment updated: [${oldPatient.assignedHealer || 'None'}] ➔ [${patientToSave.assignedHealer}]`,
        timestamp: 'Just now',
        category: 'profile_update' as const,
      });

      // Trigger credentials generation if unlocking from None
      const wasNone = !oldPatient.assignedHealer || oldPatient.assignedHealer === 'None';
      const isNowAssigned = patientToSave.assignedHealer && patientToSave.assignedHealer !== 'None';
      if (wasNone && isNowAssigned && !credentials) {
        const username = patientToSave.name.toLowerCase().replace(/\s+/g, '_') + `_${Math.floor(Math.random() * 100)}`;
        const passwordAutoGenerated = `PHMS-${Math.random().toString(36).substring(2, 7)}#`;
        credentials = {
          username,
          passwordAutoGenerated,
          smsSent: true,
          emailSent: true,
        };
        updatedActivityLogs.unshift(
          { action: `SMS login credentials dispatched for username: ${username}`, timestamp: 'Just now', category: 'profile_update' as const },
          { action: `Email login credentials dispatched for email: ${patientToSave.email}`, timestamp: 'Just now', category: 'profile_update' as const }
        );
      }
    }

    // Detect status change
    if (patientToSave.status !== oldPatient.status) {
      updatedStatusHistory.unshift({
        prevStatus: oldPatient.status || 'None',
        newStatus: patientToSave.status,
        changedBy: displayName,
        timestamp: timestampString,
      });
      updatedActivityLogs.unshift({
        action: `Patient status transitioned: [${oldPatient.status}] ➔ [${patientToSave.status}]`,
        timestamp: 'Just now',
        category: 'profile_update' as const,
      });
    }

    updatedActivityLogs.unshift({
      action: 'Personal information & medical records updated',
      timestamp: 'Just now',
      category: 'profile_update' as const,
    });

    const saved: Patient = {
      ...patientToSave,
      credentials,
      healerHistory: updatedHealerHistory,
      statusHistory: updatedStatusHistory,
      activityLogs: updatedActivityLogs,
    };

    setPatients(patients.map((p) => (p.id === patientToSave.id ? saved : p)));
    setShowEditModal(false);
  };



  // Delete Patient Profile Action
  const handleDeletePatient = (patient: Patient) => {
    const confirmDelete = window.confirm(`Are you sure you want to delete patient profile for ${patient.name} (${patient.id})?`);
    if (confirmDelete) {
      const remaining = patients.filter((p) => p.id !== patient.id);
      setPatients(remaining);
      if (selectedPatientId === patient.id) {
        if (remaining.length > 0) {
          setSelectedPatientId(remaining[0].id);
        } else {
          setSelectedPatientId('');
        }
      }
      alert(`Patient profile for ${patient.name} has been deleted successfully.`);
    }
  };

  // Global Analytics metrics calculated dynamically
  const activeCount = patients.filter((p) => p.status === 'Active').length;
  const mtdRegistered = patients.length;

  return (
    <IonPage className="sa-page">
      <IonHeader className="ion-no-border">
        <IonToolbar className="sa-page__toolbar">
          <IonButtons slot="start">
            <IonMenuButton />
          </IonButtons>
          
          <div className="db-toolbar-content">
            {/* Left Header Info */}
            <div className="db-toolbar-left">
              <h1 className="db-page-title">Patient Management</h1>
              <p className="db-page-subtitle">Patient Records, Medical Workflows and Session Tracking</p>
            </div>

            {/* Add Patient Button */}
            {viewMode === 'list' && (
              <button className="st-btn st-btn--primary" onClick={() => history.push('/branch-admin/patients/register')} style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                <IonIcon icon={addOutline} /> Add New Patient
              </button>
            )}
            
          </div>
        </IonToolbar>
      </IonHeader>

      <IonContent className="sa-page__content" fullscreen>
        <div className="sa-page__body">

          {viewMode === 'list' && (
            <>
              {/* =======================================================
                  SECTION 1: CLINICAL STATS PREVIEW PRE-CHECKS RIBBON
                 ======================================================= */}
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '16px', marginBottom: '24px' }}>
                <div className="sa-stat-card" style={{ borderLeft: '4px solid #10b981', padding: '16px', display: 'flex', flexDirection: 'column', gap: '4px' }}>
                  <span className="sa-stat-card__label">Active Cases</span>
                  <span className="sa-stat-card__value">{activeCount}</span>
                </div>
                <div className="sa-stat-card" style={{ borderLeft: '4px solid #1e3a8a', padding: '16px', display: 'flex', flexDirection: 'column', gap: '4px' }}>
                  <span className="sa-stat-card__label">Total Registered</span>
                  <span className="sa-stat-card__value">{mtdRegistered}</span>
                </div>
                <div className="sa-stat-card" style={{ borderLeft: '4px solid #f59e0b', padding: '16px', display: 'flex', flexDirection: 'column', gap: '4px' }}>
                  <span className="sa-stat-card__label">Daily Appts Queue</span>
                  <span className="sa-stat-card__value">18</span>
                </div>
                <div className="sa-stat-card" style={{ borderLeft: '4px solid #8b5cf6', padding: '16px', display: 'flex', flexDirection: 'column', gap: '4px' }}>
                  <span className="sa-stat-card__label">Documents Vaulted</span>
                  <span className="sa-stat-card__value">24</span>
                </div>
                <div className="sa-stat-card" style={{ borderLeft: '4px solid #ef4444', padding: '16px', display: 'flex', flexDirection: 'column', gap: '4px' }}>
                  <span className="sa-stat-card__label">Pending Balance</span>
                  <span className="sa-stat-card__value">₹2500</span>
                </div>
              </div>

              {/* ==========================================
                  SECTION 2: ADVANCED FILTERING & SORTING BAR
                 ========================================== */}
              <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '20px', flexWrap: 'wrap' }}>
                {/* Search Bar Input */}
                <div className="st-header-search" style={{ margin: 0, height: '36px', boxSizing: 'border-box', background: '#ffffff', width: '280px' }}>
                  <IonIcon icon={searchOutline} className="st-search-bar-icon" />
                  <input
                    type="text"
                    placeholder="Search by ID, Name, Mobile, Email..."
                    className="st-search-bar-input"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    style={{ fontSize: '12px' }}
                  />
                </div>

                <div style={{ display: 'flex', alignItems: 'center', gap: '6px', background: '#f1f5f9', padding: '0 12px', borderRadius: '8px', fontSize: '12px', fontWeight: 700, color: '#334155', height: '36px', boxSizing: 'border-box' }}>
                  <IonIcon icon={filterOutline} />
                  <span>FILTERS</span>
                </div>

                {/* Gender filter select */}
                <select
                  value={genderFilter}
                  onChange={(e) => setGenderFilter(e.target.value)}
                  style={{ height: '36px', padding: '0 12px', borderRadius: '8px', border: '1px solid #cbd5e1', background: '#ffffff', fontSize: '12px', color: '#475569', outline: 'none', fontWeight: 600, boxSizing: 'border-box' }}
                >
                  <option value="All">All Genders</option>
                  <option value="Male">Male</option>
                  <option value="Female">Female</option>
                </select>

                {/* Status filter select */}
                <select
                  value={statusFilter}
                  onChange={(e) => setStatusFilter(e.target.value)}
                  style={{ height: '36px', padding: '0 12px', borderRadius: '8px', border: '1px solid #cbd5e1', background: '#ffffff', fontSize: '12px', color: '#475569', outline: 'none', fontWeight: 600, boxSizing: 'border-box' }}
                >
                  <option value="All">All Statuses</option>
                  <option value="Active">Active</option>
                  <option value="Inactive">Inactive</option>
                </select>

                {/* Healer filter select */}
                <select
                  value={healerFilter}
                  onChange={(e) => setHealerFilter(e.target.value)}
                  style={{ height: '36px', padding: '0 12px', borderRadius: '8px', border: '1px solid #cbd5e1', background: '#ffffff', fontSize: '12px', color: '#475569', outline: 'none', fontWeight: 600, boxSizing: 'border-box' }}
                >
                  <option value="All">All Healers</option>
                  <option value="Dr. Anjali Rao">Dr. Anjali Rao</option>
                  <option value="Dr. Kevin Smith">Dr. Kevin Smith</option>
                </select>

                {/* Sorting select */}
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginLeft: 'auto', height: '36px', boxSizing: 'border-box' }}>
                  <select
                    value={sortBy}
                    onChange={(e) => setSortBy(e.target.value)}
                    style={{ height: '36px', padding: '0 12px', borderRadius: '8px', border: '1px solid #cbd5e1', background: '#ffffff', fontSize: '12px', color: '#475569', outline: 'none', fontWeight: 600, boxSizing: 'border-box' }}
                  >
                    <option value="Newest">Newest Registered</option>
                    <option value="Alphabetical">Alphabetical</option>
                    <option value="Recent Visit">Recent Visit</option>
                    <option value="Reg Date">Oldest Registered</option>
                  </select>
                </div>
              </div>

              {/* ==========================================
                  SECTION 3: PATIENT REGISTRY TABLE (12 COLS)
                 ========================================== */}
              <div className="sa-section" style={{ borderRadius: '16px', padding: '20px', marginBottom: '24px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
                  <div>
                    <h2 style={{ fontSize: '16px', fontWeight: 800, margin: 0 }}>Branch Patient Directory</h2>
                    <p style={{ fontSize: '11px', color: '#64748b', margin: '2px 0 0 0' }}>Search and select patients to view complete profile folders</p>
                  </div>

                  <div style={{ display: 'flex', gap: '10px', alignItems: 'center' }}>
                   

                  </div>
                </div>

                {/* 12-Column Table Formats */}
                <div className="st-table-container">
                  <table className="st-table">
                    <thead>
                      <tr>
                        <th>PATIENT ID</th>
                        <th>PATIENT NAME</th>
                        <th>GENDER</th>
                        <th>AGE</th>
                        <th>ASSIGNED HEALER</th>
                        <th>REG DATE</th>
                        <th>STATUS</th>
                        <th style={{ textAlign: 'center' }}>ACTIONS</th>
                      </tr>
                    </thead>
                    <tbody>
                      {sortedPatients.length > 0 ? (
                        sortedPatients.map((patient) => {
                          const isSelected = patient.id === selectedPatientId;
                          return (
                            <tr
                              key={patient.id}
                              className={`st-table-row ${isSelected ? 'st-table-row--selected' : ''}`}
                              onClick={() => { setSelectedPatientId(patient.id); setViewMode('detail'); }}
                              style={{ cursor: 'pointer', borderLeft: isSelected ? '4px solid #1f7a6a' : 'none' }}
                            >
                              <td style={{ fontWeight: '700', color: '#1f7a6a' }}>{patient.id}</td>
                              <td>
                                <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                                  <div
                                    style={{
                                      backgroundColor: patient.avatarColor,
                                      color: 'white',
                                      width: '32px',
                                      height: '32px',
                                      borderRadius: '50%',
                                      display: 'flex',
                                      alignItems: 'center',
                                      justifyContent: 'center',
                                      fontWeight: 'bold',
                                      fontSize: '11px',
                                    }}
                                  >
                                    {patient.initials}
                                  </div>
                                  <span style={{ fontWeight: '700', color: '#0f172a' }}>{patient.name}</span>
                                </div>
                              </td>
                              <td>{patient.gender}</td>
                              <td>{patient.age}</td>
                              
                              <td>{patient.assignedHealer}</td>
                              <td>{patient.regDate}</td>
                              <td>
                                <span className={`st-panel-badge ${patient.status === 'Active' ? 'st-panel-badge--green' : patient.status === 'On Hold' ? 'st-panel-badge--orange' : ''}`}>
                                  {patient.status}
                                </span>
                              </td>
                              <td style={{ textAlign: 'center' }} onClick={(e) => e.stopPropagation()}>
                                <div style={{ display: 'flex', gap: '8px', justifyContent: 'center' }}>
                                  <button className="sa-action-btn sa-action-btn--view" title="View Folder" onClick={() => { setSelectedPatientId(patient.id); setViewMode('detail'); }}>
                                    <IonIcon icon={eyeOutline} />
                                  </button>
                                  <button className="sa-action-btn sa-action-btn--edit" title="Edit Profile" onClick={() => { setSelectedPatientId(patient.id); history.push(ROUTES.BRANCH_ADMIN.EDIT_PATIENT.replace(':id', encodeURIComponent(patient.id))); }}>
                                    <IonIcon icon={pencilOutline} />
                                  </button>
                                  <button className="sa-action-btn sa-action-btn--delete" title="Delete Profile" onClick={() => handleDeletePatient(patient)}>
                                    <IonIcon icon={trashOutline} />
                                  </button>
                                </div>
                              </td>
                            </tr>
                          );
                        })
                      ) : (
                        <tr>
                          <td colSpan={10} className="st-table-empty">
                            No registered patients match your filters.
                          </td>
                        </tr>
                      )}
                    </tbody>
                  </table>
                </div>

                {/* Pagination Controls */}
                <div className="st-pagination">
                  <span className="st-pagination-info">
                    Showing {sortedPatients.length} of {patients.length} branch patients
                  </span>
                  <div className="st-pagination-controls">
                    <button className="st-page-btn" disabled>«</button>
                    <button className="st-page-btn st-page-btn--active">1</button>
                    <button className="st-page-btn" disabled>»</button>
                  </div>
                </div>
              </div>

             
            </>
          )}

          {viewMode === 'detail' && selectedPatient && (
            <DetailsPatientPage
              patient={selectedPatient}
              onBack={() => setViewMode('list')}
              onUpdatePatient={(updatedPatient) => {
                setPatients((prev) =>
                  prev.map((p) => (p.id === updatedPatient.id ? updatedPatient : p))
                );
              }}
            />
          )}


        </div>
      </IonContent>

      {/* ==========================================
          MODAL 1: ADD NEW PATIENT wizard
         ========================================== */}
      <IonModal isOpen={showAddModal} onDidDismiss={() => setShowAddModal(false)} className="sa-modal">
        <div className="sa-modal__content">
          <div className="sa-modal__header">
            <h2>Register New Patient folder</h2>
            <button className="sa-modal__close-btn" onClick={() => setShowAddModal(false)}>×</button>
          </div>
          <div className="sa-modal__body">
            <div className="st-form">
              {/* Row 1 */}
              <div className="st-form-row">
                <div className="st-form-group">
                  <label className="st-form-label">FULL PATIENT NAME *</label>
                  <input
                    type="text"
                    className="st-input"
                    placeholder="Full Name"
                    value={newPatient.name}
                    onChange={(e) => setNewPatient({ ...newPatient, name: e.target.value })}
                  />
                </div>
                <div className="st-form-group">
                  <label className="st-form-label">MOBILE NUMBER *</label>
                  <input
                    type="text"
                    className="st-input"
                    placeholder="10-digit Mobile"
                    value={newPatient.mobile}
                    onChange={(e) => setNewPatient({ ...newPatient, mobile: e.target.value })}
                  />
                </div>
              </div>

              {/* Row 2 */}
              <div className="st-form-row">
                <div className="st-form-group">
                  <label className="st-form-label">EMAIL ADDRESS *</label>
                  <input
                    type="email"
                    className="st-input"
                    placeholder="email@example.com"
                    value={newPatient.email}
                    onChange={(e) => setNewPatient({ ...newPatient, email: e.target.value })}
                  />
                </div>
                <div className="st-form-row" style={{ gap: '10px' }}>
                  <div className="st-form-group">
                    <label className="st-form-label">GENDER</label>
                    <select
                      className="st-input"
                      value={newPatient.gender}
                      onChange={(e) => setNewPatient({ ...newPatient, gender: e.target.value as any })}
                    >
                      <option value="Male">Male</option>
                      <option value="Female">Female</option>
                    </select>
                  </div>
                  <div className="st-form-group">
                    <label className="st-form-label">AGE</label>
                    <input
                      type="number"
                      className="st-input"
                      value={newPatient.age}
                      onChange={(e) => setNewPatient({ ...newPatient, age: Number(e.target.value) })}
                    />
                  </div>
                  <div className="st-form-group">
                    <label className="st-form-label">BLOOD GROUP</label>
                    <input
                      type="text"
                      className="st-input"
                      placeholder="e.g. O+"
                      value={newPatient.bloodGroup}
                      onChange={(e) => setNewPatient({ ...newPatient, bloodGroup: e.target.value })}
                    />
                  </div>
                </div>
              </div>

              {/* Row 2 - Additional Fields */}
              <div className="st-form-row">
                <div className="st-form-group">
                  <label className="st-form-label">DATE OF BIRTH</label>
                  <input
                    type="date"
                    className="st-input"
                    value={newPatient.dateOfBirth}
                    onChange={(e) => setNewPatient({ ...newPatient, dateOfBirth: e.target.value })}
                  />
                </div>
                <div className="st-form-group">
                  <label className="st-form-label">OCCUPATION</label>
                  <input
                    type="text"
                    className="st-input"
                    placeholder="Occupation"
                    value={newPatient.occupation}
                    onChange={(e) => setNewPatient({ ...newPatient, occupation: e.target.value })}
                  />
                </div>
              </div>

              {/* Row 3 */}
              <div className="st-form-row">
                <div className="st-form-group">
                  <label className="st-form-label">ASSIGNED CLINICAL HEALER</label>
                  <select
                    className="st-input"
                    value={newPatient.assignedHealer}
                    onChange={(e) => setNewPatient({ ...newPatient, assignedHealer: e.target.value })}
                  >
                    <option value="None">None (Unassigned)</option>
                    <option value="Dr. Anjali Rao">Dr. Anjali Rao</option>
                    <option value="Dr. Kevin Smith">Dr. Kevin Smith</option>
                  </select>
                </div>
              </div>

              <span className="pa-info-block-title" style={{ marginTop: '12px' }}>Emergency Contact</span>
              
              <div className="st-form-row">
                <div className="st-form-group">
                  <label className="st-form-label">CONTACT NAME</label>
                  <input
                    type="text"
                    className="st-input"
                    placeholder="Emergency Name"
                    value={newPatient.emergencyName}
                    onChange={(e) => setNewPatient({ ...newPatient, emergencyName: e.target.value })}
                  />
                </div>
                <div className="st-form-group">
                  <label className="st-form-label">RELATION</label>
                  <input
                    type="text"
                    className="st-input"
                    placeholder="Relation"
                    value={newPatient.emergencyRelation}
                    onChange={(e) => setNewPatient({ ...newPatient, emergencyRelation: e.target.value })}
                  />
                </div>
                <div className="st-form-group">
                  <label className="st-form-label">MOBILE NUMBER</label>
                  <input
                    type="text"
                    className="st-input"
                    placeholder="Emergency Mobile"
                    value={newPatient.emergencyMobile}
                    onChange={(e) => setNewPatient({ ...newPatient, emergencyMobile: e.target.value })}
                  />
                </div>
              </div>

              <span className="pa-info-block-title" style={{ marginTop: '12px' }}>Clinical Information</span>

              <div className="st-form-row">
                <div className="st-form-group">
                  <label className="st-form-label">HEALTH CONDITIONS (COMMA SEPARATED)</label>
                  <input
                    type="text"
                    className="st-input"
                    placeholder="e.g. Hypertension, Lower Back Pain"
                    value={newPatient.conditions}
                    onChange={(e) => setNewPatient({ ...newPatient, conditions: e.target.value })}
                  />
                </div>
                <div className="st-form-group">
                  <label className="st-form-label">ALLERGIES (COMMA SEPARATED)</label>
                  <input
                    type="text"
                    className="st-input"
                    placeholder="e.g. Lavender oil, Dust"
                    value={newPatient.allergies}
                    onChange={(e) => setNewPatient({ ...newPatient, allergies: e.target.value })}
                  />
                </div>
              </div>

              <div className="st-form-group">
                <label className="st-form-label">CLINICAL OBSERVATION NOTES</label>
                <textarea
                  className="st-textarea"
                  rows={2}
                  placeholder="Enter medical notes or healing specifics..."
                  value={newPatient.notes}
                  onChange={(e) => setNewPatient({ ...newPatient, notes: e.target.value })}
                />
              </div>
            </div>
          </div>
          <div className="sa-modal__footer">
            <button className="sa-btn sa-btn--outline" onClick={() => setShowAddModal(false)}>Cancel</button>
            <button className="sa-btn sa-btn--primary" onClick={handleAddPatientSubmit}>Add Patient</button>
          </div>
        </div>
      </IonModal>

      {/* ==========================================
          MODAL 2: EDIT PATIENT FORM
         ========================================== */}
      <IonModal isOpen={showEditModal} onDidDismiss={() => setShowEditModal(false)} className="sa-modal">
        <div className="sa-modal__content">
          <div className="sa-modal__header">
            <h2>Edit Patient Profile: {editForm?.name}</h2>
            <button className="sa-modal__close-btn" onClick={() => setShowEditModal(false)}>×</button>
          </div>
          <div className="sa-modal__body">
            {editForm && (
              <div className="st-form">
                <div className="st-form-row">
                  <div className="st-form-group">
                    <label className="st-form-label">FULL PATIENT NAME</label>
                    <input
                      type="text"
                      className="st-input"
                      value={editForm.name}
                      onChange={(e) => setEditForm({ ...editForm, name: e.target.value })}
                    />
                  </div>
                  <div className="st-form-group">
                    <label className="st-form-label">MOBILE NUMBER</label>
                    <input
                      type="text"
                      className="st-input"
                      value={editForm.mobile}
                      onChange={(e) => setEditForm({ ...editForm, mobile: e.target.value })}
                    />
                  </div>
                </div>

                <div className="st-form-row">
                  <div className="st-form-group">
                    <label className="st-form-label">EMAIL ADDRESS</label>
                    <input
                      type="email"
                      className="st-input"
                      value={editForm.email}
                      onChange={(e) => setEditForm({ ...editForm, email: e.target.value })}
                    />
                  </div>
                  <div className="st-form-row" style={{ gap: '10px' }}>
                    <div className="st-form-group">
                      <label className="st-form-label">AGE</label>
                      <input
                        type="number"
                        className="st-input"
                        value={editForm.age}
                        onChange={(e) => setEditForm({ ...editForm, age: Number(e.target.value) })}
                      />
                    </div>
                    <div className="st-form-group">
                      <label className="st-form-label">BLOOD GROUP</label>
                      <input
                        type="text"
                        className="st-input"
                        value={editForm.bloodGroup}
                        onChange={(e) => setEditForm({ ...editForm, bloodGroup: e.target.value })}
                      />
                    </div>
                    <div className="st-form-group">
                      <label className="st-form-label">CLINICAL STATUS</label>
                      <select
                        className="st-input"
                        value={editForm.status}
                        onChange={(e) => setEditForm({ ...editForm, status: e.target.value as any })}
                      >
                        <option value="Active">Active</option>
                        <option value="On Hold">On Hold</option>
                        <option value="Completed">Completed</option>
                        <option value="Inactive">Inactive</option>
                      </select>
                    </div>
                  </div>
                </div>

                <div className="st-form-row">
                  <div className="st-form-group">
                    <label className="st-form-label">ASSIGNED HEALER</label>
                    <select
                      className="st-input"
                      value={editForm.assignedHealer}
                      onChange={(e) => setEditForm({ ...editForm, assignedHealer: e.target.value })}
                    >
                      <option value="None">None (Unassigned)</option>
                      <option value="Dr. Anjali Rao">Dr. Anjali Rao</option>
                      <option value="Dr. Kevin Smith">Dr. Kevin Smith</option>
                    </select>
                  </div>
                </div>

                <span className="pa-info-block-title" style={{ marginTop: '12px' }}>Medical Notes</span>

                <div className="st-form-group">
                  <label className="st-form-label">CLINICAL PROFILE OVERVIEW</label>
                  <textarea
                    className="st-textarea"
                    rows={3}
                    value={editForm.medicalInfo.notes}
                    onChange={(e) => setEditForm({
                      ...editForm,
                      medicalInfo: { ...editForm.medicalInfo, notes: e.target.value }
                    })}
                  />
                </div>
              </div>
            )}
          </div>
          <div className="sa-modal__footer">
            <button className="sa-btn sa-btn--outline" onClick={() => setShowEditModal(false)}>Cancel</button>
            <button className="sa-btn sa-btn--primary" onClick={() => handleEditPatientSubmit()}>Save Changes</button>
          </div>
        </div>
      </IonModal>


    </IonPage>
  );
};

export default PatientsPage;
